import { getNodeOwnedBlocksForTransfer } from './XmlCompareTransferPreview.js';
import { createXmlCompareValidationModel } from './XmlCompareValidationModel.js';
export const XML_COMPARE_AUTO_MAP_POPUP_SCHEMA='xml-compare-auto-map-popup/v12';
const esc=(v)=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const clean=(v)=>String(v??'').trim();
const unique=(items=[])=>[...new Set(items.map(clean).filter(Boolean))];
const STYLE='<style>.xml-compare-automap-popup{position:fixed;inset:42px 24px 24px;z-index:50;background:rgba(2,6,23,.62)}.xml-compare-automap-card{height:100%;display:flex;flex-direction:column;border:1px solid rgba(125,211,252,.38);border-radius:16px;background:rgba(15,23,42,.96);overflow:hidden}.xml-compare-automap-card>header,.xml-compare-automap-panel header{display:flex;justify-content:space-between;gap:10px;padding:10px 14px;border-bottom:1px solid rgba(148,163,184,.18)}.xml-compare-automap-card b{color:#e0f2fe}.xml-compare-automap-card span,.xml-compare-automap-card small{color:#94a3b8}.xml-compare-automap-layout{display:grid;grid-template-columns:1fr 1fr;gap:12px;min-height:0;padding:12px;overflow:hidden}.xml-compare-automap-panel{min-width:0;min-height:0;border:1px solid rgba(96,165,250,.18);border-radius:12px;background:rgba(2,6,23,.30);overflow:hidden;display:flex;flex-direction:column}.xml-compare-popup-table{overflow:auto}.xml-compare-popup-table table{width:100%;border-collapse:collapse;font-size:11px}.xml-compare-popup-table th,.xml-compare-popup-table td{border-bottom:1px solid rgba(148,163,184,.12);padding:6px 7px;color:#dbeafe;vertical-align:top}.xml-compare-field-controls,.xml-compare-scope-tabs,.xml-compare-right-tabs{display:flex;gap:7px;align-items:center;flex-wrap:wrap;padding:8px 10px;border-bottom:1px solid rgba(148,163,184,.12)}.xml-compare-stage-selection-grid{display:grid;grid-template-columns:minmax(190px,1fr) auto minmax(190px,1fr);gap:8px;align-items:start;width:100%}.xml-compare-stage-selection-grid label{display:grid;gap:4px;color:#bfdbfe;font-size:11px}.xml-compare-field-controls select{min-width:190px}.xml-compare-tab-body,.xml-compare-scope-body{display:none}.xml-compare-automap-card:has(#xml-compare-toggle-transfer:checked) .is-transfer{display:block}.xml-compare-automap-card:has(#xml-compare-toggle-compare:checked) .is-compare{display:block}.xml-compare-automap-card:has(#xml-compare-scope-node:checked) .is-node-scope{display:block}.xml-compare-automap-card:has(#xml-compare-scope-element:checked) .is-element-scope{display:block}.xml-compare-automap-card:has(#xml-compare-scope-line:checked) .is-line-scope{display:block}.xml-compare-warning{margin:8px 10px;border:1px solid rgba(251,191,36,.32);border-radius:10px;padding:8px;color:#fde68a}.xml-compare-validation-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:6px;padding:8px 10px}.xml-compare-validation-summary span{border:1px solid rgba(148,163,184,.14);border-radius:8px;padding:6px;background:rgba(15,23,42,.55)}</style>';
const FIELD_PRIORITY=Object.freeze(['NodeName','FROM_NAME','TO_NAME','globalX','globalY','globalZ','TAG','GUID','DELTA_X','DELTA_Y','DELTA_Z','DIAMETER','WALL_THICK','MATERIAL_NAME','MATERIAL_NUM','LINE_ID','Branchname','SupportText']);
const BLOCK_ORDER=Object.freeze({node:['NodeNameBlock','GlobalCoordinateBlock','SupportTagGuidBlock','MiscNodeBlock'],element:['RouteGeometryBlock','SectionDimensionBlock','MiscElementBlock'],line:['LineIdentityBlock','ProcessBlock','MaterialBlock','MiscLineBlock']});
const EXCLUDED_TRANSFER_KEYS=new Set(['from','to','fromnode','tonode','from_node','to_node']);
function n(v){const x=Number(v);return Number.isFinite(x)?x:0;}
function p(record={}){const q=record.position||record.points?.[0],x=Number(q?.x),y=Number(q?.y),z=Number(q?.z);return[x,y,z].every(Number.isFinite)?{x,y,z}:null;}
function attrs(record={}){return record?.sourceAttributes||record?.attributes||record?.raw?.attributes||{};}
function normalizedKey(key=''){return clean(key).replace(/[^a-z0-9]/gi,'').toLowerCase();}
function normalizeNode(value=''){const text=clean(value),number=Number(text);return Number.isFinite(number)&&Math.abs(number-Math.round(number))<1e-6?String(Math.round(number)):text.replace(/\.0+$/,'');}
function isTransferableField(key=''){return clean(key)&&!EXCLUDED_TRANSFER_KEYS.has(normalizedKey(key));}
function rawFields(record={}){const direct={};for(const[k,v]of Object.entries(record||{})){if(v==null||typeof v==='object')continue;direct[k]=v;}return Object.freeze({...direct,...attrs(record),...(record?.transferFields||{})});}
function normalizedChildFields(record={}){const out={};for(const[k,v]of Object.entries(rawFields(record)||{})){if(!isTransferableField(k)||v==null||typeof v==='object')continue;const text=clean(v);if(text)out[clean(k)]=text;}return Object.freeze(out);}
function fieldBlock(scope='node',field=''){const k=clean(field).toUpperCase().replaceAll('-','_');if(scope==='node')return /GLOBAL_|COORD|^(GLOBALX|GLOBALY|GLOBALZ)$/.test(k)?'GlobalCoordinateBlock':(/^(FROM_NAME|TO_NAME|NODE_NAME|NODENAME|NAME)$/.test(k)?'NodeNameBlock':(/^(TAG|GUID|SUPPORT)/.test(k)?'SupportTagGuidBlock':'MiscNodeBlock'));if(scope==='element')return /^DELTA_[XYZ]$/.test(k)||/LENGTH/.test(k)?'RouteGeometryBlock':(['DIAMETER','WALL_THICK','INSUL_THICK','NOMINAL_DIAMETER'].includes(k)?'SectionDimensionBlock':'MiscElementBlock');if(/^(MATERIAL|MATERIAL_NAME|MATERIAL_NUM)/.test(k))return'MaterialBlock';if(/^(LINE_ID|BRANCH|BRANCHNAME|LINE_NO|LINENO)$/.test(k))return'LineIdentityBlock';return'MiscLineBlock';}
function fieldScope(field=''){const k=clean(field).toUpperCase().replaceAll('-','_');if(/GLOBAL_|COORD|^(GLOBALX|GLOBALY|GLOBALZ|FROM_NAME|TO_NAME|NODE_NAME|NODENAME|NAME|TAG|GUID)$/.test(k))return'node';if(/^DELTA_[XYZ]$/.test(k)||['DIAMETER','WALL_THICK','INSUL_THICK','NOMINAL_DIAMETER'].includes(k))return'element';return'line';}
function priority(field){const i=FIELD_PRIORITY.findIndex((x)=>x.toLowerCase()===clean(field).toLowerCase());return i>=0?i:1000;}
function scopedFields(rows=[],scope='node'){const names=new Set();for(const row of rows)for(const k of Object.keys(row.sourceFields||{}))if(isTransferableField(k)&&fieldScope(k)===scope)names.add(k);return[...names].sort((a,b)=>fieldBlock(scope,a).localeCompare(fieldBlock(scope,b))||priority(a)-priority(b)||a.localeCompare(b,undefined,{numeric:true,sensitivity:'base'}));}
function fieldGroups(fields=[],scope='node'){const groups=new Map();for(const f of fields){const b=fieldBlock(scope,f);if(!groups.has(b))groups.set(b,[]);groups.get(b).push(f);}return(BLOCK_ORDER[scope]||[]).filter((b)=>groups.has(b)).map((b)=>[b,groups.get(b)]);}
function applyTargetTransform(record,transform){const q=p(record);if(!q||!transform)return null;return{x:n(transform.signs?.x)*q[transform.axes?.x]+n(transform.offset?.x),y:n(transform.signs?.y)*q[transform.axes?.y]+n(transform.offset?.y),z:n(transform.signs?.z)*q[transform.axes?.z]+n(transform.offset?.z)};}
function delta(source,targetPoint){const sp=p(source);if(!sp||!targetPoint)return{dx:0,dy:0,dz:0,srss:Number.POSITIVE_INFINITY,maxAbs:Number.POSITIVE_INFINITY};const dx=targetPoint.x-sp.x,dy=targetPoint.y-sp.y,dz=targetPoint.z-sp.z;return{dx,dy,dz,srss:Math.sqrt(dx*dx+dy*dy+dz*dz),maxAbs:Math.max(Math.abs(dx),Math.abs(dy),Math.abs(dz))};}
function bestTargetForSource(source,targetRecords=[],transform=null,used=new Set()){let best=null;for(const target of targetRecords){if(used.has(target.uid))continue;const d=delta(source,applyTargetTransform(target,transform));if(!best||d.srss<best.delta.srss)best={source,target,delta:d};}return best;}
function matchedRows(matchMap={},sourceRecords=[],targetRecords=[]){const used=new Set(),rows=[];for(const source of sourceRecords){const best=bestTargetForSource(source,targetRecords,matchMap.transform,used);if(!best)continue;used.add(best.target.uid);rows.push(Object.freeze({index:rows.length,match:{},source,target:best.target,sourceFields:normalizedChildFields(source),targetFields:normalizedChildFields(best.target),delta:best.delta,type:'LEAST_DELTA'}));}return rows.sort((a,b)=>a.delta.srss-b.delta.srss||clean(a.source.uid).localeCompare(clean(b.source.uid)));}
function endpointPairFromRecord(record={}){const a=attrs(record),from=normalizeNode(a.FROM_NODE||a.fromNode||a.from||a.FROM||record.fromNode),to=normalizeNode(a.TO_NODE||a.toNode||a.to||a.TO||record.toNode);return from&&to?{from,to,key:`${from}->${to}`}:{from:'',to:'',key:clean(record.elementKey||'')};}
function nodePairMap(rows=[]){const map=new Map();for(const row of rows){const s=normalizeNode(row.source?.nodeNumber||row.match?.sourceUid),t=normalizeNode(row.target?.nodeNumber||row.match?.targetUid);if(s&&t&&!map.has(s))map.set(s,t);}return map;}
function inferElementPairsFromNodePairs(rows=[]){const map=nodePairMap(rows),pairs=new Map();for(const row of rows){const s=endpointPairFromRecord(row.source),tf=map.get(s.from),tt=map.get(s.to);if(!s.key||!tf||!tt)continue;const tk=`${tf}->${tt}`,pk=`${s.key}=>${tk}`;if(!pairs.has(pk))pairs.set(pk,{sourceElement:s.key,targetElement:tk,sourceLine:row.source?.lineNo||'',targetLine:row.target?.lineNo||'',endpointMap:{[s.from]:tf,[s.to]:tt},sourceFields:{},matchedEndpointCount:2,inference:'both-endpoint-node-pairs'});Object.assign(pairs.get(pk).sourceFields,row.sourceFields||{});}return[...pairs.values()].map((p)=>Object.freeze({...p,endpointMap:Object.freeze(p.endpointMap),sourceFields:Object.freeze(p.sourceFields)}));}
function sourceRecordPool(source=null){const out=[],seen=new Set();for(const r of[...(source?.baseRecords||[]),...(source?.intake?.records||[]),...(source?.records||[])]){const uid=clean(r?.uid);if(uid&&seen.has(uid))continue;if(uid)seen.add(uid);out.push(r);}return Object.freeze(out);}
function occurrenceRecords(model=null,preferredRecord={}){const pool=sourceRecordPool(model),node=normalizeNode(preferredRecord?.nodeNumber||''),line=clean(preferredRecord?.lineNo||'');return pool.filter((r)=>r?.levelId==='node'&&normalizeNode(r.nodeNumber)===node&&(!line||!clean(r.lineNo)||clean(r.lineNo)===line));}
function nodeBlocksForRecord(record={},model=null){return getNodeOwnedBlocksForTransfer({selectedNode:record,records:sourceRecordPool(model)});}
function blockMap(blocks=[]){return new Map(blocks.map((b)=>[clean(b.blockName),b]));}
function occurrenceBlockRows(records=[],model=null){return records.map((record)=>{const blocks=nodeBlocksForRecord(record,model);return{record,blocks,map:blockMap(blocks)};});}
function compactFields(fields={}){return Object.entries(fields||{}).slice(0,6).map(([k,v])=>`${k}=${v}`).join('; ');}
function chooseSourceOccurrence(rows=[],blockName='',preferred={}){let best=null;for(const row of rows){const block=row.map.get(blockName);if(!block)continue;const score=100+(Number(block.itemCount||0)>0?100:0)+(clean(row.record.role)===clean(preferred.role)?20:0);if(!best||score>best.score)best={...row,score};}return best;}
function chooseTargetOccurrence(rows=[],blockName='',preferred={},sourceOccurrence=null){let best=null;for(const row of rows){const block=row.map.get(blockName),score=(block?100:0)+(block&&Number(block.itemCount||0)>0?100:0)+(sourceOccurrence&&clean(row.record.role)===clean(sourceOccurrence.record.role)?40:0)+(clean(row.record.role)===clean(preferred.role)?20:0);if(!best||score>best.score)best={...row,score};}return best;}
function physicalNodeTransferCases(rows=[],source=null,target=null){const cases=[],seen=new Set();for(const row of rows){const sn=normalizeNode(row.source?.nodeNumber||row.match?.sourceUid),tn=normalizeNode(row.target?.nodeNumber||row.match?.targetUid),pk=`${clean(row.source?.lineNo)}:${sn}->${clean(row.target?.lineNo)}:${tn}`;if(!sn||!tn||seen.has(pk))continue;seen.add(pk);const sr=occurrenceBlockRows(occurrenceRecords(source,row.source),source),tr=occurrenceBlockRows(occurrenceRecords(target,row.target),target),names=unique([...sr.flatMap((x)=>x.blocks.map((b)=>b.blockName)),...tr.flatMap((x)=>x.blocks.map((b)=>b.blockName))]);for(const name of names){const so=chooseSourceOccurrence(sr,name,row.source),to=chooseTargetOccurrence(tr,name,row.target,so),sb=so?.map.get(name)||null,tb=to?.map.get(name)||null,sourceRecord=so?.record||row.source,targetRecord=to?.record||row.target,se=clean(sourceRecord?.elementKey||endpointPairFromRecord(sourceRecord).key),te=clean(targetRecord?.elementKey||endpointPairFromRecord(targetRecord).key);cases.push(Object.freeze({id:`node:${row.index}:${se}:${sn}->${te}:${tn}:${name}`,rowIndex:row.index,blockName:name,status:sb&&tb?'replace':sb&&!tb?'add':!sb&&tb?'source-missing':'none',approved:Boolean(sb),sourceBlock:sb,targetBlock:tb,sourceNode:sn,targetNode:tn,sourceRole:clean(sourceRecord?.role),targetRole:clean(targetRecord?.role),sourceElement:se,targetElement:te,sourceLine:clean(sourceRecord?.lineNo||row.source?.lineNo),targetLine:clean(targetRecord?.lineNo||row.target?.lineNo),deltaSrssMm:Number(row.delta?.srss||0),resolution:se!==clean(row.source?.elementKey)||te!==clean(row.target?.elementKey)?'physical-node-block-occurrence':'matched-row-occurrence'}));}}return Object.freeze(cases);}
function nodeTransferCases(rows=[],source=null,target=null){return physicalNodeTransferCases(rows,source,target);}
function uniqueBlockNamesFromCases(cases=[]){return Object.freeze(unique(cases.map((x)=>x.blockName)));}
function nodeTransferPlan(rows=[],fields=[],selectedBlocks=[],cases=[]){return cases.filter((x)=>x.sourceBlock&&selectedBlocks.includes(x.blockName)).map((x)=>{const row=rows.find((r)=>r.index===x.rowIndex)||{},selected={};for(const f of fields)if(row.sourceFields?.[f]!=null)selected[f]=row.sourceFields[f];return Object.freeze({id:`${x.sourceElement}:${x.sourceNode}->${x.targetElement}:${x.targetNode}:${x.blockName}`,sourceNode:x.sourceNode,sourceRole:x.sourceRole,sourceLine:x.sourceLine,sourceElement:x.sourceElement,targetNode:x.targetNode,targetRole:x.targetRole,targetLine:x.targetLine,targetElement:x.targetElement,deltaSrssMm:x.deltaSrssMm,selectedBlocks:Object.freeze([x.blockName]),approvedCaseIds:Object.freeze([x.id]),fields:Object.freeze(selected),resolution:x.resolution});});}
function elementTransferPlan(rows=[],fields=[]){return inferElementPairsFromNodePairs(rows).map((pair)=>Object.freeze({...pair,selectedBlocks:Object.freeze([...new Set(fields.map((f)=>fieldBlock('element',f)))])}));}
function lineTransferPlan(rows=[],fields=[]){const byLine=new Map();for(const row of rows){const key=`${row.source?.lineNo||''}=>${row.target?.lineNo||''}`;if(!byLine.has(key))byLine.set(key,{sourceLine:row.source?.lineNo||'',targetLine:row.target?.lineNo||'',matchedNodes:0,fields:{}});byLine.get(key).matchedNodes+=1;}return[...byLine.values()].map((x)=>Object.freeze({...x,selectedBlocks:Object.freeze([...new Set(fields.map((f)=>fieldBlock('line',f)))])}));}
function xyz(c){return c?`${Number(c.x).toFixed(3)}, ${Number(c.y).toFixed(3)}, ${Number(c.z).toFixed(3)}`:'-';}
function validationHeader(model){const mode=model.mode==='coordinate-transform-nearest'?'Coordinate transform nearest target':'Field compare';return `<header><b>Validation Panel</b><span>Anchor: Source ${esc(model.anchor?.sourceLabel||'-')} → Target ${esc(model.anchor?.targetLabel||'-')} · Mode: ${esc(mode)} · Layer: ${esc(model.validationLayer)} · Tolerance: ${Number(model.toleranceMm).toFixed(1)} mm</span></header>`;}
function renderCoordRows(rows=[]){return rows.map((r)=>`<tr><td>${esc(r.sourceLabel)}</td><td>${esc(r.targetLabel||'-')}</td><td>${esc(xyz(r.sourceCoordinate))}</td><td>${esc(xyz(r.expectedTargetCoordinate))}</td><td>${esc(xyz(r.actualTargetCoordinate))}</td><td>${Number(r.deltaX||0).toFixed(3)}</td><td>${Number(r.deltaY||0).toFixed(3)}</td><td>${Number(r.deltaZ||0).toFixed(3)}</td><td>${Number(r.srss||0).toFixed(3)}</td><td>${esc(r.status)}</td></tr>`).join('')||'<tr><td colspan="10">No validation rows.</td></tr>';}
function rowResult(r){if(r.result)return r.result;if(r.delta!=null)return Number(r.delta).toFixed(6);return'';}
function rowSource(r){return r.groupName||r.sourceValue||r.sourceGroupValue||'';}
function renderFieldValidationRows(rows=[]){return rows.map((r)=>`<tr><td>${esc(r.sourceLabel)}</td><td>${esc(r.targetLabel)}</td><td>${esc(r.field)}</td><td>${esc(r.mode||r.valueType)}</td><td>${esc(rowSource(r))}</td><td>${esc(r.targetValue||r.targetGroupValue||'')}</td><td>${esc(rowResult(r))}</td><td>${esc(r.status)}</td></tr>`).join('')||'<tr><td colspan="8">No field compare rows.</td></tr>';}
function renderValidationPanel({source=null,target=null,matchMap=null,compareFields=[]}={}){const validationLayer=matchMap?.request?.validationLayer||'current',toleranceMm=matchMap?.request?.toleranceMm??1,textRules=matchMap?.request?.textRules||{},model=createXmlCompareValidationModel({source,target,matchMap,compareFields,validationLayer,toleranceMm,textRules}),summary=`<div class="xml-compare-validation-summary"><span>Source ${model.summary.sourceCount}</span><span>Target ${model.summary.targetCount}</span><span>OK ${model.summary.okCount}</span><span>Mismatch ${model.summary.mismatchCount}</span></div>`,coordHead='<tr><th>Source Item</th><th>Nearest Target Item</th><th>Source XYZ</th><th>Expected Target XYZ</th><th>Actual Target XYZ</th><th>ΔX</th><th>ΔY</th><th>ΔZ</th><th>SRSS</th><th>Status</th></tr>',fieldHead='<tr><th>Source Item</th><th>Target Item</th><th>Field</th><th>Mode / Group</th><th>Source</th><th>Target</th><th>Result</th><th>Status</th></tr>';return `<section class="xml-compare-automap-panel">${validationHeader(model)}${summary}${model.diagnostics.length?`<div class="xml-compare-warning">${esc(model.diagnostics.join(', '))}</div>`:''}<div class="xml-compare-popup-table"><table><thead>${model.mode==='coordinate-transform-nearest'?coordHead:fieldHead}</thead><tbody>${model.mode==='coordinate-transform-nearest'?renderCoordRows(model.rows):renderFieldValidationRows(model.rows)}</tbody></table></div></section>`;}
function renderFieldOptions(fields=[],scope='node'){return fieldGroups(fields,scope).map(([block,items])=>`<optgroup label="${esc(block)}">${items.map((k)=>`<option value="${esc(k)}" selected>${esc(k)}</option>`).join('')}</optgroup>`).join('');}
function blockOptionList(blocks=[]){return blocks.map((name)=>`<option value="${esc(name)}">${esc(name)}</option>`).join('');}
function stagedSelectionControls(scope,available=[],selected=[]){return `<div class="xml-compare-stage-selection-grid"><label>Available ${esc(scope)} block(s)<select multiple size="7" data-xml-compare-transfer-${esc(scope)}-blocks>${blockOptionList(available)}</select></label><button type="button" data-xml-compare-action="stage-transfer-blocks" data-xml-compare-transfer-scope="${esc(scope)}">Add to selection</button><label>Selected ${esc(scope)} block(s)<select multiple size="7" data-xml-compare-selected-transfer-blocks>${blockOptionList(selected)}</select></label></div>`;}
function caseStatusLabel(status=''){if(status==='add')return'Source available / Target missing';if(status==='replace')return'Source available / Target available';if(status==='source-missing')return'Source missing / Target available';return'No change';}
function renderNodeCaseRows(cases=[]){return cases.map((x)=>`<tr><td><input type="checkbox" ${x.approved?'checked':''} ${x.sourceBlock?'':'disabled'} data-xml-compare-transfer-pair="${esc(x.id)}" data-block-name="${esc(x.blockName)}"></td><td>${esc(x.sourceNode)}<br><small>${esc(x.sourceElement)} ${esc(x.sourceRole)}</small></td><td>${esc(x.targetNode)}<br><small>${esc(x.targetElement)} ${esc(x.targetRole)}</small></td><td>${esc(x.blockName)}<br><small>${esc(caseStatusLabel(x.status))}</small><br><small>${esc(x.resolution)}</small></td><td>${esc(x.sourceBlock?`itemCount=${x.sourceBlock.itemCount}; ${compactFields(x.sourceBlock.compactFields||x.sourceBlock.fields)}`:'not available in Source')}</td><td>${esc(x.targetBlock?`itemCount=${x.targetBlock.itemCount}; ${compactFields(x.targetBlock.compactFields||x.targetBlock.fields)}`:'not available in Target')}</td></tr>`).join('')||'<tr><td colspan="6">No affected node-owned block cases found.</td></tr>';}
function renderRows(rows=[],fields=[],scope='node'){return rows.map((row)=>`<tr><td>${esc(scope==='line'?row.source?.lineNo:row.source?.nodeNumber||'')}</td><td>${esc(scope==='line'?row.target?.lineNo:row.target?.nodeNumber||'')}</td><td>${fields.map((key)=>`${esc(fieldBlock(scope,key))}.${esc(key)}=${esc(row.sourceFields?.[key]||'-')}`).join('<br>')}</td></tr>`).join('')||'<tr><td colspan="3">No selected pairs.</td></tr>';}
function renderElementRows(pairs=[],fields=[]){return pairs.map((p)=>`<tr><td>${esc(p.sourceElement)}</td><td>${esc(p.targetElement)}</td><td>${fields.map((k)=>`${esc(fieldBlock('element',k))}.${esc(k)}`).join('<br>')}</td></tr>`).join('')||'<tr><td colspan="3">No inferred element pairs.</td></tr>';}
function renderScopePane(scope,rows,source=null,target=null){const fields=scopedFields(rows,scope),cases=scope==='node'?nodeTransferCases(rows,source,target):[],blockNames=scope==='node'?uniqueBlockNamesFromCases(cases):[],elementPairs=scope==='element'?inferElementPairsFromNodePairs(rows):[],selectedBlocks=scope==='node'&&blockNames.length?blockNames:[...new Set(fields.map((k)=>fieldBlock(scope,k)))],plan=scope==='node'?nodeTransferPlan(rows,fields,selectedBlocks,cases):scope==='element'?elementTransferPlan(rows,fields):lineTransferPlan(rows,fields),title=scope==='node'?'Node-owned blocks':scope==='element'?'Element-owned blocks':'Line-owned blocks',operation=scope==='node'?'copy-node-owned-blocks':scope==='element'?'copy-element-owned-blocks':'copy-line-owned-blocks',selection=scope==='node'&&blockNames.length?stagedSelectionControls(scope,blockNames,selectedBlocks):`<label>${title}<br><select multiple size="8" data-xml-compare-transfer-${scope}-blocks>${renderFieldOptions(fields,scope)}</select></label>`,head=scope==='node'&&cases.length?'<tr><th>Approve</th><th>Source node</th><th>Target node</th><th>Affected block</th><th>Source A</th><th>Target B</th></tr>':`<tr><th>Source ${scope}</th><th>Target ${scope}</th><th>Preview values</th></tr>`,body=scope==='node'&&cases.length?renderNodeCaseRows(cases):(scope==='element'?renderElementRows(elementPairs,fields):renderRows(rows,fields,scope));return `<div class="xml-compare-scope-body is-${scope}-scope"><div class="xml-compare-field-controls">${selection}</div><div class="xml-compare-popup-table"><table><thead>${head}</thead><tbody>${body}</tbody></table></div><details open><summary>${title} preview JSON</summary><pre>${esc(JSON.stringify({mode:'preview-only',transferScope:scope,operation,pairScope:scope==='element'?'all-inferred-element-pairs':'all-matched-physical-node-pairs',selectedBlocks,pairs:plan,approvedPairIds:scope==='node'?cases.filter((x)=>x.approved&&selectedBlocks.includes(x.blockName)).map((x)=>x.id):undefined,affectedBlockCases:scope==='node'?cases:undefined},null,2))}</pre></details></div>`;}
function renderTransferPanel(rows=[],source=null,target=null){return `<section class="xml-compare-automap-panel"><header><b>Transfer</b><span>approval-gated preview only</span></header><div class="xml-compare-right-tabs"><input id="xml-compare-toggle-transfer" name="xml-compare-popup-right" type="radio"><label class="xml-compare-toggle" for="xml-compare-toggle-transfer">Transfer</label><input id="xml-compare-toggle-compare" name="xml-compare-popup-right" type="radio" checked><label class="xml-compare-toggle" for="xml-compare-toggle-compare">Compare</label></div><div class="xml-compare-tab-body is-transfer"><div class="xml-compare-scope-tabs"><b>Transfer scope:</b><input id="xml-compare-scope-node" name="xml-compare-transfer-scope" type="radio" checked><label class="xml-compare-toggle" for="xml-compare-scope-node">Node blocks</label><input id="xml-compare-scope-element" name="xml-compare-transfer-scope" type="radio"><label class="xml-compare-toggle" for="xml-compare-scope-element">Element blocks</label><input id="xml-compare-scope-line" name="xml-compare-transfer-scope" type="radio"><label class="xml-compare-toggle" for="xml-compare-scope-line">Line blocks</label></div>${renderScopePane('node',rows,source,target)}${renderScopePane('element',rows,source,target)}${renderScopePane('line',rows,source,target)}</div><div class="xml-compare-tab-body is-compare"><small>Field-compare fallback is shown in the Validation Panel.</small></div></section>`;}
export function renderXmlCompareAutoMapPopupHtml({matchMap=null,source=null,target=null,compareFields=[]}={}){if(!matchMap?.request)return'';const rows=matchedRows(matchMap,source?.records||[],target?.records||[]);return `${STYLE}<aside class="xml-compare-automap-popup" data-xml-compare-automap-popup><div class="xml-compare-automap-card"><header><div><b>Auto Map Review</b><span>${esc(matchMap.request.scope||'item')} anchor · validation</span></div><button type="button" data-xml-compare-action="clear-auto-map">Close</button></header><div class="xml-compare-automap-layout">${renderValidationPanel({source,target,matchMap,compareFields})}${renderTransferPanel(rows,source,target)}</div></div></aside>`;}
export const _test=Object.freeze({esc,attrs,normalizedChildFields,fieldBlock,fieldScope,scopedFields,matchedRows,nodeTransferCases,nodeTransferPlan,renderValidationPanel,renderFieldValidationRows});
