import { createXmlCompareLoadIntake } from './XmlCompareLoadIntake.js';
import { detectXmlCompareProfile, XML_COMPARE_PROFILE_TYPES } from './XmlCompareProfileDetector.js';
import { createXmlCompareLineNodeHierarchy } from './XmlCompareLineNodeHierarchy.js';
import { createXmlComparePnmAutoMap } from './XmlComparePnmAutoMapper.js';
import { adaptCiiEnrichedXmlToCompareRecords } from './XmlCompareCiiEnrichedXmlAdapter.js';
import { parseCiiEnrichedStageJson } from './XmlCompareCiiEnrichedStageAdapter.js';
import { createXmlCompareCanvasLevelModel } from './XmlCompareCanvasLevelModel.js';
import { createXmlCompareConnectorCandidateModel } from './XmlCompareConnectorCandidateModel.js';
import { normalizeCompareFields } from './XmlCompareFieldCompareModel.js';
export const XML_COMPARE_WORKSPACE_MODEL_SCHEMA='xml-compare-workspace-model/v9';
const clean=(v)=>String(v??'').trim();
const LEVEL_RECORD_LAYOUTS=new Set(['cards','tiles','compact-list','grouped-tree','grouped-compact-tree']);
function sourceName(file,name){return clean(file?.name||name);}
function position(record={}){return record.position||record.points?.[0]||record.centrePoint||record.coOrds||null;}
function recordsFromDataset(dataset=null){const components=Array.isArray(dataset?.components)?dataset.components:[];return Object.freeze(components.map((component,index)=>Object.freeze({uid:clean(component.id)||`component:${index+1}`,nodeNumber:clean(component.id),nodeName:clean(component.label),componentType:clean(component.type),componentRefNo:clean(component.id),branchName:clean(component.pipelineRef),lineNo:clean(component.pipelineRef),position:position(component),points:component.points||[],raw:component}))) }
function emptyAdapter(){return Object.freeze({records:Object.freeze([]),diagnostics:Object.freeze([]),summary:Object.freeze({})});}
function enrichedAdapterRecords(detected,text,side,name){try{if(detected.type===XML_COMPARE_PROFILE_TYPES.CII_ENRICHED_XML)return adaptCiiEnrichedXmlToCompareRecords(text,{side,sourceName:name});if(detected.type===XML_COMPARE_PROFILE_TYPES.CII_ENRICHED_STAGE)return parseCiiEnrichedStageJson(text,{side,sourceName:name});return emptyAdapter();}catch(error){return Object.freeze({records:Object.freeze([]),diagnostics:Object.freeze([{code:'XML-COMPARE-CII-ADAPTER-FAILED',message:clean(error?.message||error),sourceName:name}]),summary:Object.freeze({diagnosticCount:1})});}}
function summaryNodeCount(hierarchy,intake,adapter,reportDataset){return Number(reportDataset?.componentCount||0)||hierarchy.nodeCount||Number(adapter.summary?.nodeCount||0)||Number(intake.summary?.nodeCount||0)||Number(intake.summary?.recordCount||0)||0;}
function shouldUseLevelRecords(detected,levelView,levelSelection){const layout=clean(levelView?.layout);const explicitLevel=clean(levelSelection?.levelId);if(explicitLevel&&LEVEL_RECORD_LAYOUTS.has(layout))return true;return detected?.type===XML_COMPARE_PROFILE_TYPES.CATEGORIZED_XML&&['tiles','compact-list','grouped-tree','grouped-compact-tree'].includes(layout);}
function sideModel({side,file=null,text='',name='',reportDataset=null,levelSelection=null}={}){const loaded=Boolean(file||clean(text)||reportDataset);const fileName=loaded?sourceName(file,name):'';const sideName=clean(side)||'source';const detected=detectXmlCompareProfile({name:fileName,text});const intake=createXmlCompareLoadIntake({name:fileName,text,profile:detected.type});const adapted=enrichedAdapterRecords(detected,text,sideName,fileName);const reportRecords=recordsFromDataset(reportDataset);const adaptedRecords=Array.isArray(adapted.records)?adapted.records:[];const baseRecords=reportRecords.length?reportRecords:(adaptedRecords.length?adaptedRecords:intake.records);const baseHierarchy=createXmlCompareLineNodeHierarchy(baseRecords);const mergedSummary={...intake.summary,...(adapted.summary||{}),lineCount:baseHierarchy.lineCount,nodeCount:baseHierarchy.nodeCount};const levelView=createXmlCompareCanvasLevelModel({side:sideName,fileName,profile:detected.type,records:baseRecords,summary:mergedSummary,selection:levelSelection||{}});const useLevelRecords=shouldUseLevelRecords(detected,levelView,levelSelection||{});const records=useLevelRecords?levelView.records:baseHierarchy.records;const hierarchy=useLevelRecords?createXmlCompareLineNodeHierarchy(levelView.records):baseHierarchy;const summary=Object.freeze({...intake.summary,...(adapted.summary||{}),recordCount:baseRecords.length,visibleRecordCount:records.length,nodeCount:summaryNodeCount(hierarchy,intake,adapted,reportDataset),lineCount:intake.summary?.lineCount||hierarchy.lineCount,diagnosticCount:(adapted.diagnostics?.length||0),activeLevel:levelView.levelId});return Object.freeze({side:sideName,fileName:fileName||detected.sourceName,profile:detected.type,type:detected.type,summary,confidence:detected.confidence,reason:detected.reason,records,hierarchy,baseRecords:Object.freeze(baseRecords),intake,adapter:adapted,diagnostics:Object.freeze(adapted.diagnostics||[]),levelProfile:levelView.hierarchyProfile,levelView:Object.freeze({...levelView,records})});}
function log(code,message){return Object.freeze({ts:'',level:'info',code:clean(code),message:clean(message)});}
function loadMessage(side){return `${side.fileName}: ${side.summary.recordCount||0} load record(s), ${side.summary.lineCount||0} line(s), ${side.summary.nodeCount||0} node(s), profile ${side.profile}`;}
function emptyAutoMap(request=null){return Object.freeze({schema:'xml-compare-pnm-auto-mapper/v1',matches:Object.freeze([]),transform:null,request:request||null,summary:Object.freeze({matchCount:0,conflictCount:0,ambiguousCount:0,rejectedCount:0,worstMm:0,avgMm:0})});}
function byUid(records=[],uid=''){return records.find((record)=>clean(record.uid)===clean(uid))||null;}
function sampleLine(records=[],lineNo='',selectedUid=''){const same=(records||[]).filter((record)=>clean(record.lineNo)===clean(lineNo));if(!same.length)return byUid(records,selectedUid)?[byUid(records,selectedUid)]:[];const selected=byUid(same,selectedUid);const rest=same.filter((record)=>record!==selected);return Object.freeze([...(selected?[selected]:[]),...rest].slice(0,5));}
function scopedRecords(records=[],request=null,side='source'){if(!request)return Object.freeze([]);const uid=side==='source'?request.sourceUid:request.targetUid;const lineNo=side==='source'?request.sourceLineNo:request.targetLineNo;if(request.scope==='line')return sampleLine(records,lineNo,uid);const selected=byUid(records,uid);return Object.freeze(selected?[selected]:[]);}
function buildAutoMap(source,target,request=null,compareFields=[]){if(!request)return emptyAutoMap(null);const sourceRecords=scopedRecords(source.records,request,'source');const targetRecords=scopedRecords(target.records,request,'target');const nextRequest=Object.freeze({...request,compareFields:normalizeCompareFields(request.compareFields?.length?request.compareFields:compareFields)});if(!sourceRecords.length||!targetRecords.length)return emptyAutoMap(nextRequest);const map=createXmlComparePnmAutoMap({sourceRecords,targetRecords});return Object.freeze({...map,request:nextRequest});}
function activeDiagnostics(source,target,report){const reportDiagnostics=[...(report?.parseErrors||[]).map((message)=>Object.freeze({code:'XML-COMPARE-PARSE-ERROR',message})),...(report?.topologyIssues?.issues||[]).slice(0,40).map((issue)=>Object.freeze({code:issue.code,uid:issue.componentId,message:issue.message}))];return Object.freeze(report?reportDiagnostics:[...source.diagnostics,...target.diagnostics,...reportDiagnostics]);}
export function createXmlCompareWorkspaceModel({fileA=null,textA='',fileB=null,textB='',report=null,canvasState=null}={}){const compareFields=normalizeCompareFields(canvasState?.compareFields||[]);const source=sideModel({side:'source',file:fileA,text:textA,name:'XML A',reportDataset:report?.datasets?.A,levelSelection:canvasState?.levelViews?.source});const target=sideModel({side:'target',file:fileB,text:textB,name:'XML B',reportDataset:report?.datasets?.B,levelSelection:canvasState?.levelViews?.target});const matchMap=buildAutoMap(source,target,canvasState?.autoMapRequest||null,compareFields);const connectorCandidates=createXmlCompareConnectorCandidateModel({source,target});const diagnostics=activeDiagnostics(source,target,report);const logs=[];if(source.fileName)logs.push(log('XML-COMPARE-SOURCE-READY',loadMessage(source)));if(target.fileName)logs.push(log('XML-COMPARE-TARGET-READY',loadMessage(target)));if(connectorCandidates.summary.candidateCount)logs.push(log('XML-COMPARE-CANDIDATES',`${connectorCandidates.summary.candidateCount} preview candidate(s).`));if(canvasState?.autoMapRequest)logs.push(log('XML-COMPARE-AUTO-MAP',`${matchMap.summary.matchCount} item connector(s), scope ${canvasState.autoMapRequest.scope}.`));if(compareFields.length)logs.push(log('XML-COMPARE-COMPARE-FIELDS',`${compareFields.length} compare field(s) selected.`));if(report)logs.push(log('XML-COMPARE-REPORT-READY',`${report.topologyIssues?.summary?.issueCount||0} issue(s)`));logs.push(...(canvasState?.logs||[]));return Object.freeze({schema:XML_COMPARE_WORKSPACE_MODEL_SCHEMA,source,target,navStates:Object.freeze({source:canvasState?.source||null,target:canvasState?.target||null}),manualConnectors:Object.freeze(canvasState?.manualConnectors||[]),matchMap,connectorCandidates,compareFields,diagnostics,logs:Object.freeze(logs)});}
export const _test=Object.freeze({clean,sourceName,sideModel,recordsFromDataset,buildAutoMap,summaryNodeCount,loadMessage,scopedRecords,sampleLine,emptyAutoMap,enrichedAdapterRecords,activeDiagnostics,shouldUseLevelRecords});
