import { renderXmlCompareCanvasToolbarHtml } from './XmlCompareCanvasToolbar.js';
import { createXmlCompareFitCommand } from './XmlCompareFitController.js';
import { renderXmlCompareHoverCardHtml } from './XmlCompareHoverInspector.js';
export const XML_COMPARE_CANVAS_HOST_SCHEMA='xml-compare-canvas-host/v2';
const esc=(v)=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
function metric(label,value){return `<div><b>${esc(label)}</b><span>${esc(value)}</span></div>`;}
function firstRecord(data={},navState={}){const records=Array.isArray(data.records)?data.records:[];return data.selectedRecord||data.hoverRecord||records.find((r)=>r.uid===navState?.hoveredUid)||records.find((r)=>r.uid===navState?.selectedUid)||records[0]||null;}
function nodeLabel(record={},index=0){return record.componentType||record.nodeNumber||record.componentRefNo||`N${index+1}`;}
function nodeSubLabel(record={}){return record.nodeName||record.componentRefNo||record.branchName||record.uid||'';}
function nodePoint(index,total,side){if(total<=1)return {x:50,y:50};const columns=Math.min(4,Math.ceil(Math.sqrt(total)));const rows=Math.ceil(total/columns);const col=index%columns,row=Math.floor(index/columns);const x=columns<=1?50:16+(col*(68/Math.max(1,columns-1)));const y=rows<=1?50:18+(row*(64/Math.max(1,rows-1)));return {x:side==='source'?Math.min(78,x):Math.max(22,x),y};}
function graphicalNodes(records=[],navState={},side='source'){return records.slice(0,80).map((record,index)=>{const p=nodePoint(index,Math.min(records.length,80),side);const selected=record.uid===navState?.selectedUid;const hovered=record.uid===navState?.hoveredUid;return `<button type="button" id="xml-compare-node-${esc(side)}-${esc(record.uid)}" data-xml-compare-record-uid="${esc(record.uid)}" class="xml-compare-graph-node ${selected?'is-selected':''} ${hovered?'is-hovered':''}" style="left:${p.x}%;top:${p.y}%" title="${esc(nodeSubLabel(record))}"><b>${esc(nodeLabel(record,index))}</b><span>${esc(nodeSubLabel(record))}</span></button>`;}).join('');}
export function createXmlCompareCanvasHostModel({side='source',title='',data={},navState=null}={}){const records=Array.isArray(data.records)?data.records:[];const fit=createXmlCompareFitCommand({side,records});return Object.freeze({schema:XML_COMPARE_CANVAS_HOST_SCHEMA,side,title:title||side,profile:data.profile||data.type||'',recordCount:Number(data.summary?.nodeCount??data.componentCount??records.length??0),activeMode:navState?.mode||'select',fitOk:fit.ok,fitCount:fit.bounds?.count||0,records:Object.freeze(records),hoverRecord:firstRecord(data,navState||{}),bounds:fit.bounds,navState});}
export function renderXmlCompareCanvasHostHtml(input={}){const model=createXmlCompareCanvasHostModel(input);return `<section class="xml-compare-canvas-host is-graphical" data-xml-compare-canvas-host="${esc(model.side)}"><header><b>${esc(model.title)}</b><span>${esc(model.profile||'not indexed')}</span></header>${renderXmlCompareCanvasToolbarHtml({side:model.side,activeMode:model.activeMode})}<div class="xml-compare-canvas-viewport xml-compare-graph-canvas" data-xml-compare-canvas-viewport="${esc(model.side)}"><div class="xml-compare-canvas-reticle">${esc(model.side.toUpperCase())}</div>${model.records.length?graphicalNodes(model.records,model.navState||{},model.side):'<div class="xml-compare-graph-empty">No records loaded</div>'}<div class="xml-compare-canvas-metrics">${metric('Records',model.recordCount)}${metric('Fit All',model.fitOk?'ready':'empty')}${metric('Fit points',model.fitCount)}</div></div>${renderXmlCompareHoverCardHtml(model.hoverRecord)}</section>`;}
export const _test=Object.freeze({esc,firstRecord,graphicalNodes,nodePoint});
