import { createTextValidationRows } from './XmlCompareTextValidationRules.js';
export const XML_COMPARE_VALIDATION_MODEL_SCHEMA='xml-compare-validation-model/v2';

const clean=(v)=>String(v??'').trim();
const key=(v)=>clean(v).replace(/[^a-z0-9]/gi,'').toLowerCase();
const num=(v)=>{const n=Number(v);return Number.isFinite(n)?n:null;};
const label=(r)=>clean(r?.displayName||r?.nodeName||r?.nodeNumber||r?.componentRefNo||r?.lineNo||r?.uid);
const GROUPS=Object.freeze([{name:'nodeGlobal',x:'globalX',y:'globalY',z:'globalZ'},{name:'upperGlobal',x:'GLOBAL_X',y:'GLOBAL_Y',z:'GLOBAL_Z'},{name:'fromGlobalUpper',x:'FROM_GLOBAL_X',y:'FROM_GLOBAL_Y',z:'FROM_GLOBAL_Z'},{name:'fromGlobalCamel',x:'fromGlobalX',y:'fromGlobalY',z:'fromGlobalZ'},{name:'toGlobalUpper',x:'TO_GLOBAL_X',y:'TO_GLOBAL_Y',z:'TO_GLOBAL_Z'},{name:'toGlobalCamel',x:'toGlobalX',y:'toGlobalY',z:'toGlobalZ'},{name:'generic',x:'x',y:'y',z:'z'}]);
const LAYERS=Object.freeze({line:'lineBlock',lineblock:'lineBlock',current:'current',element:'element',node:'node',evidence:'nodeEvidence',nodeevidence:'nodeEvidence'});
const LEVELS=Object.freeze({lineBlock:['lineBlock','LINE_BLOCK'],element:['element','ELEMENT'],node:['node','NODE'],nodeEvidence:['nodeEvidence','NODE_EVIDENCE']});
export function normalizeValidationLayer(value){return LAYERS[key(value)]||'current';}
export function normalizeToleranceMm(value){const n=Number(value);return Number.isFinite(n)&&n>=0?n:1;}
export function readRecordField(record={},field=''){const names=[field,clean(field),clean(field).toUpperCase()];const bags=[record,record?.attributes,record?.fields,record?.compactFields,record?.sourceAttributes,record?.transferFields,record?.rawSummary];for(const bag of bags)for(const name of names)if(bag&&bag[name]!=null)return bag[name];const wanted=key(field);for(const bag of bags)for(const[k,v]of Object.entries(bag||{}))if(key(k)===wanted)return v;return undefined;}
export function detectCoordinateFieldGroup(compareFields=[]){const selected=new Set((compareFields||[]).map(key));return GROUPS.find((g)=>selected.has(key(g.x))&&selected.has(key(g.y))&&selected.has(key(g.z)))||null;}
export function recordCoordinate(record={},coordinateGroup=null){if(!coordinateGroup)return null;const x=num(readRecordField(record,coordinateGroup.x)),y=num(readRecordField(record,coordinateGroup.y)),z=num(readRecordField(record,coordinateGroup.z));return[x,y,z].every((v)=>v!=null)?Object.freeze({x,y,z}):null;}
export function createAnchorTransform({sourceAnchor=null,targetAnchor=null,coordinateGroup=null}={}){const sourceCoordinate=recordCoordinate(sourceAnchor,coordinateGroup),targetCoordinate=recordCoordinate(targetAnchor,coordinateGroup);if(!sourceCoordinate||!targetCoordinate)return null;return Object.freeze({offset:Object.freeze({x:targetCoordinate.x-sourceCoordinate.x,y:targetCoordinate.y-sourceCoordinate.y,z:targetCoordinate.z-sourceCoordinate.z}),sourceCoordinate,targetCoordinate});}
export function applyAnchorTransform(sourceCoordinate=null,transform=null){if(!sourceCoordinate||!transform?.offset)return null;return Object.freeze({x:sourceCoordinate.x+transform.offset.x,y:sourceCoordinate.y+transform.offset.y,z:sourceCoordinate.z+transform.offset.z});}
export function distance3d(a=null,b=null){if(!a||!b)return Number.POSITIVE_INFINITY;const dx=b.x-a.x,dy=b.y-a.y,dz=b.z-a.z;return Math.sqrt(dx*dx+dy*dy+dz*dz);}
export function findNearestTargetRecord({expectedCoordinate=null,targetRecords=[],coordinateGroup=null}={}){let best=null;for(const record of targetRecords||[]){const actual=recordCoordinate(record,coordinateGroup);if(!actual)continue;const srss=distance3d(expectedCoordinate,actual);if(!best||srss<best.srss)best={record,coordinate:actual,srss};}return best?Object.freeze(best):null;}
function pool(side={}){const out=[],seen=new Set();for(const r of[...(side?.baseRecords||[]),...(side?.intake?.records||[]),...(side?.records||[])]){const id=clean(r?.uid)||`${clean(r?.levelId)}:${out.length}`;if(seen.has(id))continue;seen.add(id);out.push(r);}return out;}
function activeLayer(source={},target={},layer='current'){const resolved=normalizeValidationLayer(layer);if(resolved!=='current')return resolved;const view=normalizeValidationLayer(source?.levelView?.levelId||target?.levelView?.levelId||'node');return view==='current'?'node':view;}
function matchesLayer(record={},layer='node'){const allowed=LEVELS[layer]||LEVELS.node;return allowed.includes(clean(record.levelId))||allowed.includes(clean(record.recordKind));}
export function recordsForValidationLayer({source=null,target=null,layer='current'}={}){const validationLayer=activeLayer(source,target,layer);return Object.freeze({validationLayer,sourceRecords:Object.freeze(pool(source).filter((r)=>matchesLayer(r,validationLayer))),targetRecords:Object.freeze(pool(target).filter((r)=>matchesLayer(r,validationLayer)))});}
function byUid(records=[],uid=''){return(records||[]).find((r)=>clean(r?.uid)===clean(uid))||null;}
function anchorFromRequest(sourceRecords=[],targetRecords=[],matchMap={}){const req=matchMap?.request||{},sourceAnchor=byUid(sourceRecords,req.sourceUid),targetAnchor=byUid(targetRecords,req.targetUid);if(sourceAnchor&&targetAnchor)return{sourceAnchor,targetAnchor};const first=(matchMap?.matches||[])[0]||{};return{sourceAnchor:byUid(sourceRecords,first.sourceUid),targetAnchor:byUid(targetRecords,first.targetUid)};}
function emptySummary(sourceCount=0,targetCount=0){return{sourceCount,targetCount,validatedCount:0,okCount:0,mismatchCount:0,missingCoordinateCount:0,noTargetCount:0,duplicateNearestTargetCount:0,maxSrss:0};}
function coordStatus(srss,tol){return srss<=tol?'OK':'MISMATCH';}
function coordRow(sourceRecord,nearest,sourceCoordinate,expected,toleranceMm){if(!sourceCoordinate)return{sourceUid:clean(sourceRecord?.uid),sourceLabel:label(sourceRecord),status:'MISSING_SOURCE_COORDINATE'};if(!nearest)return{sourceUid:clean(sourceRecord?.uid),sourceLabel:label(sourceRecord),sourceCoordinate,expectedTargetCoordinate:expected,status:'NO_TARGET_NEARBY'};const a=nearest.coordinate,dx=a.x-expected.x,dy=a.y-expected.y,dz=a.z-expected.z;return{sourceUid:clean(sourceRecord?.uid),targetUid:clean(nearest.record?.uid),sourceLabel:label(sourceRecord),targetLabel:label(nearest.record),sourceCoordinate,expectedTargetCoordinate:expected,actualTargetCoordinate:a,deltaX:dx,deltaY:dy,deltaZ:dz,srss:nearest.srss,status:coordStatus(nearest.srss,toleranceMm)};}
function summarizeRows(rows=[],sourceCount=0,targetCount=0){const nearest=rows.map((r)=>r.targetUid).filter(Boolean),dupes=nearest.filter((id,i)=>nearest.indexOf(id)!==i);return{sourceCount,targetCount,validatedCount:rows.length,okCount:rows.filter((r)=>r.status==='OK'||r.status==='WITHIN_TOLERANCE').length,mismatchCount:rows.filter((r)=>!['OK','WITHIN_TOLERANCE'].includes(r.status)).length,missingCoordinateCount:rows.filter((r)=>r.status==='MISSING_SOURCE_COORDINATE'||r.status==='MISSING_TARGET_COORDINATE').length,noTargetCount:rows.filter((r)=>r.status==='NO_TARGET_NEARBY').length,duplicateNearestTargetCount:new Set(dupes).size,maxSrss:Math.max(0,...rows.map((r)=>Number(r.srss)||0))};}
function valuesFor(record,fields=[]){return Object.fromEntries((fields||[]).map((f)=>[f,readRecordField(record,f)??'']));}
function numericRows(sourceAnchor,targetAnchor,fields=[]){return fields.map((field)=>{const s=readRecordField(sourceAnchor,field),t=readRecordField(targetAnchor,field),sv=num(s),tv=num(t);return sv!=null&&tv!=null?{rowType:'numeric',sourceUid:clean(sourceAnchor?.uid),targetUid:clean(targetAnchor?.uid),sourceLabel:label(sourceAnchor),targetLabel:label(targetAnchor),field,sourceValue:s??'',targetValue:t??'',valueType:'number',mode:'numeric-delta',delta:tv-sv,status:sv===tv?'OK':'MISMATCH'}:null;}).filter(Boolean);}
function fieldCompareRows(sourceAnchor,targetAnchor,compareFields=[],textRules={}){const numeric=numericRows(sourceAnchor,targetAnchor,compareFields),numericFields=new Set(numeric.map((r)=>r.field)),textFields=compareFields.filter((f)=>!numericFields.has(f));const sourceRecord={uid:sourceAnchor?.uid,displayName:label(sourceAnchor),...valuesFor(sourceAnchor,textFields)},targetRecord={uid:targetAnchor?.uid,displayName:label(targetAnchor),...valuesFor(targetAnchor,textFields)};return Object.freeze([...numeric,...createTextValidationRows({sourceRecord,targetRecord,compareFields:textFields,textRules})]);}
function publicBase(base={}){return{validationLayer:base.validationLayer,compareFields:base.compareFields,coordinateGroup:base.coordinateGroup,toleranceMm:base.toleranceMm,anchor:base.anchor};}
function fieldCompareModel(args,base,diagnostics=[]){const rows=base.sourceAnchor&&base.targetAnchor?fieldCompareRows(base.sourceAnchor,base.targetAnchor,args.compareFields,args.textRules):[];return{...publicBase(base),schema:XML_COMPARE_VALIDATION_MODEL_SCHEMA,mode:'field-compare',rows:Object.freeze(rows),summary:Object.freeze({...emptySummary(rows.length?1:0,rows.length?1:0),validatedCount:rows.length,okCount:rows.filter((r)=>r.status==='OK').length,mismatchCount:rows.filter((r)=>r.status!=='OK').length}),diagnostics:Object.freeze(diagnostics)};}
export function createXmlCompareValidationModel({source=null,target=null,matchMap=null,compareFields=[],validationLayer='current',toleranceMm=1,textRules={}}={}){const fields=Object.freeze((compareFields||[]).map(clean).filter(Boolean)),coordinateGroup=detectCoordinateFieldGroup(fields),tolerance=normalizeToleranceMm(toleranceMm),layerSet=recordsForValidationLayer({source,target,layer:validationLayer}),anchors=anchorFromRequest(layerSet.sourceRecords,layerSet.targetRecords,matchMap||{});const base={validationLayer:layerSet.validationLayer,compareFields:fields,coordinateGroup,toleranceMm:tolerance,anchor:{sourceUid:clean(anchors.sourceAnchor?.uid),targetUid:clean(anchors.targetAnchor?.uid),sourceLabel:label(anchors.sourceAnchor),targetLabel:label(anchors.targetAnchor)},sourceAnchor:anchors.sourceAnchor,targetAnchor:anchors.targetAnchor};if(!anchors.sourceAnchor||!anchors.targetAnchor)return fieldCompareModel({compareFields:fields,textRules},base,['ANCHOR_MISSING']);if(!coordinateGroup)return fieldCompareModel({compareFields:fields,textRules},base,[]);const transform=createAnchorTransform({sourceAnchor:anchors.sourceAnchor,targetAnchor:anchors.targetAnchor,coordinateGroup});if(!transform)return{...publicBase(base),schema:XML_COMPARE_VALIDATION_MODEL_SCHEMA,mode:'coordinate-transform-nearest',rows:Object.freeze([]),anchor:{...base.anchor},summary:Object.freeze(emptySummary(layerSet.sourceRecords.length,layerSet.targetRecords.length)),diagnostics:Object.freeze(['ANCHOR_COORDINATE_MISSING'])};const rows=layerSet.sourceRecords.map((record)=>{const sc=recordCoordinate(record,coordinateGroup),expected=applyAnchorTransform(sc,transform),nearest=findNearestTargetRecord({expectedCoordinate:expected,targetRecords:layerSet.targetRecords,coordinateGroup});return coordRow(record,nearest,sc,expected,tolerance);});return{schema:XML_COMPARE_VALIDATION_MODEL_SCHEMA,mode:'coordinate-transform-nearest',validationLayer:layerSet.validationLayer,compareFields:fields,coordinateGroup,toleranceMm:tolerance,anchor:Object.freeze({...base.anchor,sourceCoordinate:transform.sourceCoordinate,targetCoordinate:transform.targetCoordinate,offset:transform.offset}),rows:Object.freeze(rows),summary:Object.freeze(summarizeRows(rows,layerSet.sourceRecords.length,layerSet.targetRecords.length)),diagnostics:Object.freeze([])};}
