export const XML_COMPARE_CII_ENRICHED_STAGE_ADAPTER_SCHEMA='xml-compare-cii-enriched-stage-adapter/v1';
const clean=(v)=>String(v??'').trim();
const arr=(v)=>Array.isArray(v)?v:[];
const num=(v)=>{const n=Number(v);return Number.isFinite(n)?n:null;};
function point(v){if(!v)return null;if(Array.isArray(v)&&v.length>=3)return point({x:v[0],y:v[1],z:v[2]});const s=clean(v);if(typeof v==='string'){const p=s.match(/-?\d+(?:\.\d+)?(?:[Ee][-+]?\d+)?/g)?.map(Number)||[];return p.length>=3?Object.freeze({x:p[0],y:p[1],z:p[2]}):null;}if(typeof v==='object'){const x=num(v.x??v.X),y=num(v.y??v.Y),z=num(v.z??v.Z);return x==null||y==null||z==null?null:Object.freeze({x,y,z});}return null;}
function branchProcess(branch={}){return Object.freeze({pressure1:clean(branch.pressure?.Pressure1),hydroPressure:clean(branch.pressure?.HydroPressure),temperature1:clean(branch.temperature?.Temperature1),temperature2:clean(branch.temperature?.Temperature2),temperature3:clean(branch.temperature?.Temperature3),fluidDensity:clean(branch.fluidDensity),materialNumber:clean(branch.materialNumber)});}
function uid(side,branch,node,index){const key=[branch.branchName,branch.lineNo||branch.pipelineReference,node.nodeNumber,node.componentRefNo,node.endpoint,index+1].map(clean).filter(Boolean).join(':');return `${clean(side)||'source'}:${key||`cii-node:${index+1}`}`;}
export function normalizeCiiEnrichedStageNode(node={},branch={},index=0,{side='source'}={}){const process=branchProcess(branch);const position=point(node.position);const record={side:clean(side)||'source',profile:'xml-cii2019-enriched-stage',branchName:clean(branch.branchName),lineId:clean(branch.lineNo||branch.pipelineReference),pipelineReference:clean(branch.pipelineReference),lineNo:clean(branch.lineNo),nodeNumber:clean(node.nodeNumber),nodeName:clean(node.nodeName),endpoint:clean(node.endpoint),componentType:clean(node.componentType||'UNKNOWN').toUpperCase(),componentRefNo:clean(node.componentRefNo),position,fromPosition:position,toPosition:null,lengthMm:num(node.elementLengthMm),pipingClass:clean(node.pipingClass),rating:clean(node.rating),materialName:clean(node.materialName),materialCode:clean(node.materialCode),wallThickness:clean(node.wallThickness),corrosionAllowance:clean(node.corrosionAllowance),boreMm:clean(node.boreMm),dtxrPs:clean(node.dtxrPs),dtxrPos:clean(node.dtxrPos),process,raw:node};return Object.freeze({uid:uid(record.side,branch,node,index),...record,psNames:Object.freeze([record.nodeName,record.dtxrPs,record.dtxrPos].filter(Boolean)),diagnostics:Object.freeze([])});}
export function adaptCiiEnrichedStageToCompareRecords(stage={},options={}){const side=clean(options.side||'source')||'source';const diagnostics=[];const records=[];for(const branch of arr(stage.branches)){if(!clean(branch.branchName))diagnostics.push(Object.freeze({code:'XML-COMPARE-CII-BRANCH-NAME-MISSING'}));for(const node of arr(branch.nodes)){const record=normalizeCiiEnrichedStageNode(node,branch,records.length,{side});if(!record.nodeNumber)diagnostics.push(Object.freeze({code:'XML-COMPARE-CII-NODE-NUMBER-MISSING',uid:record.uid,branchName:record.branchName}));if(!record.position)diagnostics.push(Object.freeze({code:'XML-COMPARE-CII-NODE-POSITION-MISSING',uid:record.uid,nodeNumber:record.nodeNumber}));if(!record.componentType||record.componentType==='UNKNOWN')diagnostics.push(Object.freeze({code:'XML-COMPARE-CII-COMPONENT-TYPE-MISSING',uid:record.uid}));records.push(record);}}
return Object.freeze({schema:XML_COMPARE_CII_ENRICHED_STAGE_ADAPTER_SCHEMA,profile:'xml-cii2019-enriched-stage',side,source:clean(stage.source),enrichedXml:clean(stage.enrichedXml),records:Object.freeze(records),diagnostics:Object.freeze(diagnostics),summary:Object.freeze({branchCount:arr(stage.branches).length,nodeCount:records.length,diagnosticCount:diagnostics.length})});}
export function parseCiiEnrichedStageJson(textValue,options={}){const parsed=JSON.parse(clean(textValue)||'{}');return adaptCiiEnrichedStageToCompareRecords(parsed,options);}
export const _test=Object.freeze({clean,point,branchProcess});
