export const XML_COMPARE_LINE_NODE_HIERARCHY_SCHEMA='xml-compare-line-node-hierarchy/v3';
const clean=(v)=>String(v??'').trim();
const num=(v)=>{const n=Number(v);return Number.isFinite(n)?n:null;};
const TRANSFER_KEYS=Object.freeze(['Temperature1','Temperature2','Temperature3','Pressure1','Pressure2','Pressure3','T1','T2','T3','P1','P2','P3','PIPING_CLASS','MATERIAL','WALL_THICK','CORROSION_ALLOWANCE']);
function nodeText(v){const n=Number(v);return Number.isFinite(n)?String(n).replace(/\.0+$/,''):clean(v);}
function point(value=null){if(!value)return null;const x=num(value.x??value.X),y=num(value.y??value.Y),z=num(value.z??value.Z);return x==null||y==null||z==null?null:Object.freeze({x,y,z});}
function attrs(record={}){return record.attributes||record.raw?.attributes||record.raw||{};}
function transferFields(record={}){const a=attrs(record),out={};for(const key of TRANSFER_KEYS){const value=a[key]??a[key.toUpperCase?.()]??a[`COMPONENT-ATTRIBUTE${key.replace(/\D/g,'')}`];if(value!=null&&clean(value))out[key]=clean(value);}if(a['COMPONENT-ATTRIBUTE1']!=null)out.P1=clean(a['COMPONENT-ATTRIBUTE1']);if(a['COMPONENT-ATTRIBUTE2']!=null)out.T1=clean(a['COMPONENT-ATTRIBUTE2']);if(a['COMPONENT-ATTRIBUTE3']!=null)out.MATERIAL=clean(a['COMPONENT-ATTRIBUTE3']);if(a['COMPONENT-ATTRIBUTE4']!=null)out.WALL_THICK=clean(a['COMPONENT-ATTRIBUTE4']);return Object.freeze(out);}
function lineNo(record={}){const raw=record.raw||{};const src=raw.source||record.source||{};const a=raw.attributes||record.attributes||{};return clean(record.lineNo||record.branchName||src.lineNo||a.LINE_NO||a['PIPELINE-REFERENCE']||'UNSPECIFIED_LINE');}
function rawNode(record={},key='from'){const raw=record.raw||{};const src=raw.source||record.source||{};const a=raw.attributes||record.attributes||{};if(key==='from')return nodeText(src.from||src.fromNode||a.FROM_NODE||a.FROM_NAME||a.FROM);return nodeText(src.to||src.toNode||a.TO_NODE||a.TO_NAME||a.TO);}
function fallbackNode(record={},index=0){return nodeText(record.nodeNumber||record.nodeName||record.componentRefNo||record.uid||`NODE_${index+1}`);}
function fallbackUid(record={},index=0){return clean(record.uid||record.componentRefNo||record.nodeNumber||`record:${index}`);}
function endpointRows(record={},index=0){const pts=Array.isArray(record.points)?record.points:[];const from=rawNode(record,'from'),to=rawNode(record,'to');const rows=[];if(from&&point(pts[0]))rows.push({nodeNo:from,position:point(pts[0]),role:'from'});if(to&&point(pts[1]))rows.push({nodeNo:to,position:point(pts[1]),role:'to'});if(rows.length)return rows;const pos=point(record.position)||point(record.centrePoint)||point(record.coOrds)||point(pts[0]);return pos?[{nodeNo:fallbackNode(record,index),position:pos,role:'node',uid:fallbackUid(record,index)}]:[];}
function mergeTransferFields(a={},b={}){return Object.freeze({...a,...b});}
function cleanAttributes(source={}){const out={};for(const [key,value] of Object.entries(source||{})){if(!clean(key)||value==null)continue;if(typeof value==='object')continue;const text=clean(value);if(text)out[clean(key)]=text;}return out;}
function mergeAttributes(a={},b={}){return Object.freeze({...cleanAttributes(a),...cleanAttributes(b)});}
function addNode(lineMap,record,index,row){const line=lineNo(record);if(!lineMap.has(line))lineMap.set(line,new Map());const nodes=lineMap.get(line);const key=row.nodeNo;const sourceId=clean(record.uid||record.componentRefNo||record.id||`record:${index}`);const fields=transferFields(record);const sourceAttributes=cleanAttributes(attrs(record));if(!nodes.has(key)){nodes.set(key,Object.freeze({uid:clean(row.uid)||`${line}::${key}`,recordKind:'NODE',componentType:'NODE',lineNo:line,branchName:line,nodeNumber:key,nodeName:`Node ${key}`,position:row.position,points:Object.freeze([row.position]),transferFields:fields,sourceAttributes:Object.freeze(sourceAttributes),sourceComponentIds:Object.freeze([sourceId]),raw:Object.freeze({lineNo:line,nodeNo:key,role:row.role})}));return;}const prev=nodes.get(key);nodes.set(key,Object.freeze({...prev,transferFields:mergeTransferFields(prev.transferFields,fields),sourceAttributes:mergeAttributes(prev.sourceAttributes,sourceAttributes),sourceComponentIds:Object.freeze([...prev.sourceComponentIds,sourceId].filter(Boolean))}));}
export function createXmlCompareLineNodeHierarchy(records=[]){const lineMap=new Map();for(const [index,record] of (Array.isArray(records)?records:[]).entries())for(const row of endpointRows(record,index))addNode(lineMap,record,index,row);const lines=[...lineMap.entries()].sort((a,b)=>a[0].localeCompare(b[0],undefined,{numeric:true})).map(([line,nodes])=>Object.freeze({uid:`line::${line}`,lineNo:line,nodes:Object.freeze([...nodes.values()].sort((a,b)=>String(a.nodeNumber).localeCompare(String(b.nodeNumber),undefined,{numeric:true})))}));return Object.freeze({schema:XML_COMPARE_LINE_NODE_HIERARCHY_SCHEMA,lines:Object.freeze(lines),records:Object.freeze(lines.flatMap((line)=>line.nodes)),lineCount:lines.length,nodeCount:lines.reduce((sum,line)=>sum+line.nodes.length,0)});}
export const _test=Object.freeze({clean,nodeText,point,lineNo,rawNode,endpointRows,transferFields,attrs,cleanAttributes,mergeAttributes});
