export const XML_COMPARE_MATCH_MAP_SCHEMA='xml-compare-match-map/v1';
export const XML_COMPARE_MATCH_STATUSES=Object.freeze({ACCEPTED:'accepted',AMBIGUOUS:'ambiguous',REJECTED:'rejected',MANUAL:'manual'});
export const XML_COMPARE_MATCH_BASIS=Object.freeze({PS_NAME:'ps-name',MANUAL:'manual',LINE_SEQUENCE:'line-sequence',LENGTH:'length',COORDINATE:'coordinate'});
export const XML_COMPARE_MATCH_BASIS_PRIORITY=Object.freeze({[XML_COMPARE_MATCH_BASIS.MANUAL]:100,[XML_COMPARE_MATCH_BASIS.PS_NAME]:90,[XML_COMPARE_MATCH_BASIS.LINE_SEQUENCE]:70,[XML_COMPARE_MATCH_BASIS.LENGTH]:50,[XML_COMPARE_MATCH_BASIS.COORDINATE]:40});
const clean=(v)=>String(v??'').trim();
const arr=(v)=>Array.isArray(v)?v:(v==null?[]:[v]);
const uniq=(v)=>[...new Set(arr(v).map(clean).filter(Boolean))];
const clamp01=(v,f=0)=>{const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.min(1,n)):f;};
function priority(basis){return uniq(basis).reduce((m,b)=>Math.max(m,XML_COMPARE_MATCH_BASIS_PRIORITY[b]||0),0);}
function status(value,basis){const v=clean(value).toLowerCase();if(Object.values(XML_COMPARE_MATCH_STATUSES).includes(v))return v;return uniq(basis).includes(XML_COMPARE_MATCH_BASIS.MANUAL)?XML_COMPARE_MATCH_STATUSES.MANUAL:XML_COMPARE_MATCH_STATUSES.ACCEPTED;}
function rank(a,b){const p=priority(a?.basis)-priority(b?.basis);if(p)return p;const c=clamp01(a?.confidence)-clamp01(b?.confidence);if(c)return c;return clean(a?.id).localeCompare(clean(b?.id));}
function dist(a,b){if(!a||!b)return Number.POSITIVE_INFINITY;const dx=Number(a.x??a.X)-Number(b.x??b.X);const dy=Number(a.y??a.Y)-Number(b.y??b.Y);const dz=Number(a.z??a.Z)-Number(b.z??b.Z);return [dx,dy,dz].every(Number.isFinite)?Math.sqrt(dx*dx+dy*dy+dz*dz):Number.POSITIVE_INFINITY;}
export function normalizeXmlCompareMatch(match={}){const sourceUid=clean(match.sourceUid||match.sourceId||match.source?.uid);const targetUid=clean(match.targetUid||match.targetId||match.target?.uid);const basis=uniq(match.basis||match.bases||[]);return Object.freeze({id:clean(match.id)||`${sourceUid}->${targetUid}`,sourceUid,targetUid,basis:Object.freeze(basis),confidence:clamp01(match.confidence,priority(basis)/100||0),status:status(match.status,basis),orientation:clean(match.orientation||'unknown')||'unknown',evidence:Object.freeze({...match.evidence}),nodeMap:Object.freeze({...match.nodeMap}),diagnostics:Object.freeze(arr(match.diagnostics).map(x=>Object.freeze({...x})))})}
export function buildNodeRoleMap(sourceRecord={},targetRecord={},orientation='same'){const sf=clean(sourceRecord.fromNode),st=clean(sourceRecord.toNode),tf=clean(targetRecord.fromNode),tt=clean(targetRecord.toNode);const out={};if(orientation==='reversed'){if(sf&&tt)out[sf]=tt;if(st&&tf)out[st]=tf;return Object.freeze(out)}if(sf&&tf)out[sf]=tf;if(st&&tt)out[st]=tt;return Object.freeze(out)}
export function resolveElementOrientation(sourceRecord={},targetRecord={},transformPoint=null){const s0=sourceRecord.fromPosition||sourceRecord.points?.[0],s1=sourceRecord.toPosition||sourceRecord.points?.[1],t0=targetRecord.fromPosition||targetRecord.points?.[0],t1=targetRecord.toPosition||targetRecord.points?.[1];if(!s0||!s1||!t0||!t1)return'unknown';const x0=typeof transformPoint==='function'?transformPoint(s0):s0,x1=typeof transformPoint==='function'?transformPoint(s1):s1;const direct=dist(x0,t0)+dist(x1,t1),reverse=dist(x0,t1)+dist(x1,t0);if(!Number.isFinite(direct)||!Number.isFinite(reverse)||Math.abs(direct-reverse)<=1e-6)return'unknown';return reverse<direct?'reversed':'same'}
export function createXmlCompareMatchMap({sourceId='source',targetId='target',matches=[],ambiguous=[],rejected=[],unmatchedSourceUids=[],unmatchedTargetUids=[],settings={}}={}){const bySource=new Map(),byTarget=new Map(),conflicts=[];for(const match of arr(matches).map(normalizeXmlCompareMatch)){const ps=bySource.get(match.sourceUid),pt=byTarget.get(match.targetUid);if(!ps&&!pt){bySource.set(match.sourceUid,match);byTarget.set(match.targetUid,match);continue}const winner=[ps,pt,match].filter(Boolean).sort(rank).at(-1);conflicts.push(Object.freeze({sourceUid:match.sourceUid,targetUid:match.targetUid,winnerId:winner.id}));if(winner===match){if(ps)byTarget.delete(ps.targetUid);if(pt)bySource.delete(pt.sourceUid);bySource.set(match.sourceUid,match);byTarget.set(match.targetUid,match)}}const finalMatches=[...bySource.values()].sort((a,b)=>a.id.localeCompare(b.id));const basisCounts=finalMatches.reduce((acc,m)=>{for(const b of m.basis)acc[b]=(acc[b]||0)+1;return acc},{});const summary=Object.freeze({matchCount:finalMatches.length,ambiguousCount:arr(ambiguous).length,rejectedCount:arr(rejected).length,conflictCount:conflicts.length,unmatchedSourceCount:uniq(unmatchedSourceUids).length,unmatchedTargetCount:uniq(unmatchedTargetUids).length,basisCounts});return Object.freeze({schema:XML_COMPARE_MATCH_MAP_SCHEMA,sourceId:clean(sourceId),targetId:clean(targetId),matches:Object.freeze(finalMatches),ambiguous:Object.freeze(arr(ambiguous).map(x=>Object.freeze({...x}))),rejected:Object.freeze(arr(rejected).map(normalizeXmlCompareMatch)),conflicts:Object.freeze(conflicts),unmatchedSourceUids:Object.freeze(uniq(unmatchedSourceUids)),unmatchedTargetUids:Object.freeze(uniq(unmatchedTargetUids)),settings:Object.freeze({...settings}),summary,bySourceUid:Object.freeze(Object.fromEntries(finalMatches.map(m=>[m.sourceUid,m]))),byTargetUid:Object.freeze(Object.fromEntries(finalMatches.map(m=>[m.targetUid,m])))});}
export function summarizeXmlCompareMatchMap(map={}){const s=map.summary||{};return{matchCount:Number(s.matchCount||0),ambiguousCount:Number(s.ambiguousCount||0),rejectedCount:Number(s.rejectedCount||0),conflictCount:Number(s.conflictCount||0),unmatchedSourceCount:Number(s.unmatchedSourceCount||0),unmatchedTargetCount:Number(s.unmatchedTargetCount||0),basisCounts:{...(s.basisCounts||{})}}}
export const _test=Object.freeze({clean,priority,rank,dist});
