export const XML_COMPARE_GRAPH_CONNECTOR_LANE_SCHEMA='xml-compare-graph-connector-lane/v6';
const esc=(v)=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
function connectorLabel(conn={}){if(conn.locked)return'MANUAL';if(conn.type==='EXACT')return'AUTO';if(conn.type==='CANDIDATE')return'CAND';if(conn.type)return conn.type.replace('APPROX_','A');return'LINK';}
function connectorLine(conn,index,total){const y=total<=1?50:16+(index*(68/Math.max(1,total-1)));const cls=conn.locked?'is-locked':conn.type==='EXACT'?'is-auto-exact':conn.type==='CANDIDATE'?'is-candidate':'is-auto-approx';return `<g class="xml-compare-connector-line ${cls}" data-xml-compare-connector-id="${esc(conn.id)}"><path d="M 4 ${y} C 32 ${Math.max(8,y-18)}, 68 ${Math.min(92,y+18)}, 96 ${y}"/><circle cx="4" cy="${y}" r="2.8"/><circle cx="96" cy="${y}" r="2.8"/><text x="50" y="${Math.max(10,y-5)}">${esc(connectorLabel(conn))}</text></g>`;}
function pairKey(c={}){return `${c.sourceUid}->${c.targetUid}`;}
function allConnectors(manualConnectors=[],autoConnectors=[],candidateConnectors=[]){const locked=new Set([...manualConnectors,...autoConnectors].map(pairKey));return Object.freeze([...manualConnectors,...autoConnectors,...candidateConnectors.filter((c)=>!locked.has(pairKey(c)))]);}
function actionPanel(){return `<div class="xml-compare-auto-map-actions"><button type="button" data-xml-compare-action="auto-map-node">Auto Map Selected Node</button><button type="button" data-xml-compare-action="auto-map-line">Auto Map Selected Line</button><button type="button" data-xml-compare-action="clear-auto-map">Clear Auto</button></div>`;}
function candidateAction(action,id,label){return `<button type="button" data-xml-compare-candidate-action="${esc(action)}" data-xml-compare-candidate-id="${esc(id)}">${esc(label)}</button>`;}
function candidateRows(candidates=[],enabled=false){if(!enabled)return '<small>Manual-first mode: automatic candidate suggestions are off.</small>';if(!candidates.length)return '<small>No preview candidates at the selected levels/fields.</small>';return `<div class="xml-compare-candidate-list">${candidates.slice(0,5).map((c)=>`<article data-xml-compare-candidate-row="${esc(c.id)}" data-source-uid="${esc(c.sourceUid)}" data-target-uid="${esc(c.targetUid)}"><small><b>${esc(c.sourceLabel)}</b> → <b>${esc(c.targetLabel)}</b><br>${esc(c.sourceField)} = ${esc(c.sourceValue)}</small><div class="xml-compare-candidate-actions">${candidateAction('accept',c.id,'Accept')}${candidateAction('reject',c.id,'Reject')}</div></article>`).join('')}</div>`;}
export function renderXmlCompareGraphConnectorLaneHtml({manualState=null,matchMap=null,connectorCandidates=null}={}){const manualConnectors=Array.isArray(manualState?.connectors)?manualState.connectors:[];const autoConnectors=Array.isArray(matchMap?.matches)?matchMap.matches:[];const candidateEnabled=connectorCandidates?.summary?.enabled===true;const candidateConnectors=candidateEnabled&&Array.isArray(connectorCandidates?.candidates)?connectorCandidates.candidates:[];const connectors=allConnectors(manualConnectors,autoConnectors,candidateConnectors);const pendingSourceUid=manualState?.pendingSourceUid||'';const autoScope=matchMap?.request?.scope||'not-run';return `<section class="xml-compare-graph-connector-lane" data-xml-compare-graph-connector-lane data-xml-compare-connector-overlay><header><b>Connectors</b><span>Source → Target</span></header>${actionPanel()}<div class="xml-compare-graph-connector-counts"><div><b>Manual</b><span>${manualConnectors.length}</span></div><div><b>Auto</b><span>${autoConnectors.length}</span></div><div><b>Mode</b><span>${candidateEnabled?'Candidates':'Manual'}</span></div><div><b>Scope</b><span>${esc(autoScope)}</span></div><div><b>Pending</b><span>${pendingSourceUid?'1':'0'}</span></div></div><svg viewBox="0 0 100 100" preserveAspectRatio="none" class="xml-compare-graph-connector-svg">${connectors.map((conn,index)=>connectorLine(conn,index,connectors.length)).join('')}${pendingSourceUid&&!connectors.length?'<g class="xml-compare-connector-line is-pending"><path d="M 4 50 C 32 30, 68 70, 96 50"/><circle cx="4" cy="50" r="2.8"/><text x="50" y="43">PICK TARGET</text></g>':''}</svg>${candidateRows(candidateConnectors,candidateEnabled)}<small>Select one Source node and one Target node to create a manual connector.</small></section>`;}
export const _test=Object.freeze({esc,connectorLabel,pairKey,allConnectors,actionPanel,candidateAction,candidateRows});
