import { createXmlCompareHierarchyProfile } from './XmlCompareHierarchyProfiler.js';
export const XML_COMPARE_CANVAS_LEVEL_MODEL_SCHEMA='xml-compare-canvas-level-model/v2';
const clean=(v)=>String(v??'').trim();
const aliasLevel=(levelId)=>{const id=clean(levelId);if(id==='line')return 'lineBlock';if(id==='evidence')return 'nodeEvidence';return id;};
function has(level,field){return (level?.fields||[]).includes(clean(field));}
function pickField(level,requested='',fallback=[]){const req=clean(requested);if(req&&has(level,req))return req;return fallback.find((f)=>has(level,f))||level?.fields?.[0]||'';}
function pickLevel(profile,requested=''){const req=aliasLevel(requested);return profile.levels.find((level)=>level.levelId===req)||profile.levels.find((level)=>level.levelId==='node')||profile.levels[0]||null;}
function selectionFor(level,selection={}){return Object.freeze({levelId:level?.levelId||'',displayField:pickField(level,selection.displayField,['displayName','nodeNumber','branchName','lineNo','elementKey','evidenceKind','value','fileName']),keyField:pickField(level,selection.keyField,['key','nodeNumber','branchName','lineNo','elementKey','value','uid'])});}
const isDynamicCategorized=(records=[])=>records.some((record)=>['lineBlock','nodeEvidence'].includes(clean(record.levelId))||clean(record.recordKind)==='LINE_BLOCK');
function layoutFor(profile='',levelId='',records=[],level=null){if(level?.layout)return clean(level.layout);const p=clean(profile),id=clean(levelId);if(p==='categorized-inputxml'&&isDynamicCategorized(records)){if(id==='lineBlock')return records.length>60?'compact-list':'tiles';if(id==='element')return records.length>80?'grouped-compact-tree':'grouped-tree';if(id==='node')return records.length>120?'grouped-compact-tree':'grouped-tree';if(id==='nodeEvidence')return 'grouped-compact-tree';}if((records||[]).some((record)=>clean(record.levelHint)))return 'cards';return id==='node'?'line-node':'cards';}
export function createXmlCompareCanvasLevelModel({side='source',fileName='',profile='unknown',records=[],summary={},selection={}}={}){const hierarchyProfile=createXmlCompareHierarchyProfile({side,fileName,profile,records,summary});const active=pickLevel(hierarchyProfile,selection.levelId);const picked=selectionFor(active,selection);const activeRecords=Object.freeze(active?.records||[]);return Object.freeze({schema:XML_COMPARE_CANVAS_LEVEL_MODEL_SCHEMA,side:clean(side)||'source',hierarchyProfile,levelId:picked.levelId,label:active?.label||'',levelType:active?.levelType||'',fields:Object.freeze(active?.fields||[]),records:activeRecords,displayField:picked.displayField,keyField:picked.keyField,layout:layoutFor(profile,picked.levelId,activeRecords,active)});}
export const _test=Object.freeze({clean,aliasLevel,has,pickField,pickLevel,selectionFor,layoutFor,isDynamicCategorized});
