export const XML_COMPARE_PNM_AUTO_MAPPER_SCHEMA='xml-compare-pnm-auto-mapper/v1';
const AXES=Object.freeze(['x','y','z']);
const SIGN_SETS=Object.freeze([[1,1,1],[1,1,-1],[1,-1,1],[1,-1,-1],[-1,1,1],[-1,1,-1],[-1,-1,1],[-1,-1,-1]]);
const clean=(v)=>String(v??'').trim();
const n=(v)=>{const x=Number(v);return Number.isFinite(x)?x:null;};
function p(record={}){const q=record.position||record.points?.[0];const x=n(q?.x),y=n(q?.y),z=n(q?.z);return x==null||y==null||z==null?null:{x,y,z};}
function perms(v){return [[v[0],v[1],v[2]],[v[0],v[2],v[1]],[v[1],v[0],v[2]],[v[1],v[2],v[0]],[v[2],v[0],v[1]],[v[2],v[1],v[0]]];}
function makeTransform(source,target,axes,signs){const sp=p(source),tp=p(target),offset={};for(let i=0;i<AXES.length;i+=1){const axis=AXES[i];offset[axis]=sp[axis]-signs[i]*tp[axes[i]];}return Object.freeze({axes:Object.freeze({x:axes[0],y:axes[1],z:axes[2]}),signs:Object.freeze({x:signs[0],y:signs[1],z:signs[2]}),offset:Object.freeze(offset),anchorSourceUid:source.uid,anchorTargetUid:target.uid});}
function applyTransform(record,transform){const q=p(record);return Object.freeze({x:transform.signs.x*q[transform.axes.x]+transform.offset.x,y:transform.signs.y*q[transform.axes.y]+transform.offset.y,z:transform.signs.z*q[transform.axes.z]+transform.offset.z});}
function delta(a,b){const dx=b.x-a.x,dy=b.y-a.y,dz=b.z-a.z;return Object.freeze({dx,dy,dz,maxAbs:Math.max(Math.abs(dx),Math.abs(dy),Math.abs(dz)),euclid:Math.sqrt(dx*dx+dy*dy+dz*dz)});}
function classify(d,tol){if(d.maxAbs<=tol.exact)return'EXACT';if(d.maxAbs<=tol.approx1)return'APPROX_1';if(d.maxAbs<=tol.approx2)return'APPROX_2';if(d.maxAbs<=tol.approx3)return'APPROX_3';return'NO_MATCH';}
function rank(type){return type==='EXACT'?0:type==='APPROX_1'?1:type==='APPROX_2'?2:type==='APPROX_3'?3:99;}
function candidates(transform,sourceRecords,targetRecords,tol){const out=[];for(const s of sourceRecords){const sp=p(s);if(!sp)continue;for(const t of targetRecords){if(!p(t))continue;const tp=applyTransform(t,transform);const d=delta(sp,tp);const type=classify(d,tol);if(type==='NO_MATCH')continue;const sameLine=clean(s.lineNo)===clean(t.lineNo);out.push(Object.freeze({source:s,target:t,targetTransformed:tp,delta:d,type,rank:rank(type),sameLine}));}}out.sort((a,b)=>a.rank-b.rank||a.delta.maxAbs-b.delta.maxAbs||a.delta.euclid-b.delta.euclid||(a.sameLine===b.sameLine?0:(a.sameLine?-1:1))||clean(a.source.uid).localeCompare(clean(b.source.uid)));return out;}
function scoreTransform(transform,sourceRecords,targetRecords,tol){const usedSource=new Set(),usedTarget=new Set(),matches=[];for(const item of candidates(transform,sourceRecords,targetRecords,tol)){if(usedSource.has(item.source.uid)||usedTarget.has(item.target.uid))continue;usedSource.add(item.source.uid);usedTarget.add(item.target.uid);matches.push(item);}const counts={exact:0,approx1:0,approx2:0,approx3:0,line:0};for(const m of matches){if(m.type==='EXACT')counts.exact+=1;else if(m.type==='APPROX_1')counts.approx1+=1;else if(m.type==='APPROX_2')counts.approx2+=1;else if(m.type==='APPROX_3')counts.approx3+=1;if(m.sameLine)counts.line+=1;}const worst=matches.reduce((v,m)=>Math.max(v,m.delta.maxAbs),0);const avg=matches.length?matches.reduce((sum,m)=>sum+m.delta.maxAbs,0)/matches.length:0;const score=counts.exact*100000+counts.approx1*50000+counts.approx2*20000+counts.approx3*10000+counts.line*2000-worst*2-avg;return Object.freeze({transform,matches:Object.freeze(matches),counts:Object.freeze(counts),worst,avg,score});}
function bestTransform(sourceRecords,targetRecords,tol){let best=null;for(const s of sourceRecords.filter(p))for(const t of targetRecords.filter(p))for(const axes of perms(AXES))for(const signs of SIGN_SETS){const scored=scoreTransform(makeTransform(s,t,axes,signs),sourceRecords,targetRecords,tol);if(!best||scored.score>best.score||(scored.score===best.score&&scored.matches.length>best.matches.length)||(scored.score===best.score&&scored.matches.length===best.matches.length&&scored.avg<best.avg))best=scored;}return best;}
function confidence(type){return type==='EXACT'?1:type==='APPROX_1'?0.9:type==='APPROX_2'?0.75:type==='APPROX_3'?0.55:0;}
export function createXmlComparePnmAutoMap({sourceRecords=[],targetRecords=[],tolerance=null}={}){const src=(Array.isArray(sourceRecords)?sourceRecords:[]).filter(p),tgt=(Array.isArray(targetRecords)?targetRecords:[]).filter(p);const tol={exact:Number(tolerance?.exact??0.01),approx1:Number(tolerance?.approx1??25),approx2:Number(tolerance?.approx2??125),approx3:Number(tolerance?.approx3??1000)};const best=src.length&&tgt.length?bestTransform(src,tgt,tol):null;const matches=(best?.matches||[]).map((m)=>Object.freeze({id:`auto:${m.source.uid}->${m.target.uid}`,sourceUid:m.source.uid,targetUid:m.target.uid,sourceLabel:`${m.source.lineNo}/${m.source.nodeNumber}`,targetLabel:`${m.target.lineNo}/${m.target.nodeNumber}`,basis:Object.freeze(['coordinate-transform','line-node']),status:m.type==='EXACT'?'accepted':'approximate',confidence:confidence(m.type),locked:false,delta:m.delta,type:m.type,sameLine:m.sameLine}));return Object.freeze({schema:XML_COMPARE_PNM_AUTO_MAPPER_SCHEMA,matches:Object.freeze(matches),transform:best?.transform||null,summary:Object.freeze({matchCount:matches.length,conflictCount:0,ambiguousCount:0,rejectedCount:0,worstMm:best?.worst||0,avgMm:best?.avg||0})});}
export const _test=Object.freeze({p,perms,makeTransform,applyTransform,delta,classify,bestTransform});
