export const XML_COMPARE_LOG_SCREEN_SCHEMA='xml-compare-log-screen/v1';
export const XML_COMPARE_LOG_LEVELS=Object.freeze({DEBUG:'debug',INFO:'info',WARN:'warn',ERROR:'error'});
const clean=(v)=>String(v??'').trim();
const esc=(v)=>clean(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
function level(value){const v=clean(value).toLowerCase();return Object.values(XML_COMPARE_LOG_LEVELS).includes(v)?v:XML_COMPARE_LOG_LEVELS.INFO;}
export function createXmlCompareLogEntry({level:logLevel=XML_COMPARE_LOG_LEVELS.INFO,code='XML-COMPARE-LOG',message='',details=null,source='xml-compare'}={}){return Object.freeze({schema:XML_COMPARE_LOG_SCREEN_SCHEMA,ts:new Date().toISOString(),level:level(logLevel),code:clean(code)||'XML-COMPARE-LOG',message:clean(message),source:clean(source)||'xml-compare',details});}
export function createXmlCompareLogStore({limit=200,entries=[]}={}){const max=Math.max(1,Math.min(1000,Number(limit)||200));let rows=entries.map((entry)=>createXmlCompareLogEntry(entry)).slice(-max);const listeners=new Set();const notify=()=>{for(const fn of listeners)fn(Object.freeze([...rows]));};return Object.freeze({append(entry){rows=[...rows,createXmlCompareLogEntry(entry)].slice(-max);notify();return rows.at(-1);},clear(){rows=[];notify();},list(){return Object.freeze([...rows]);},subscribe(fn){if(typeof fn!=='function')return()=>{};listeners.add(fn);return()=>listeners.delete(fn);},snapshot(){return Object.freeze({schema:XML_COMPARE_LOG_SCREEN_SCHEMA,limit:max,count:rows.length,entries:Object.freeze([...rows])});}});}
export function appendXmlCompareLogEntry(store,entry){if(store&&typeof store.append==='function')return store.append(entry);return createXmlCompareLogEntry(entry);}
export function renderXmlCompareLogScreenHtml(input=[]){const entries=Array.isArray(input)?input:(typeof input?.list==='function'?input.list():input?.entries||[]);return `<section class="xml-compare-log-screen" data-xml-compare-log-screen><header><b>XML Compare Log</b><span>${entries.length} event${entries.length===1?'':'s'}</span></header><div class="xml-compare-log-screen-rows">${entries.map((entry)=>`<article class="xml-compare-log-row level-${esc(entry.level)}"><time>${esc(entry.ts)}</time><b>${esc(entry.code)}</b><span>${esc(entry.message)}</span></article>`).join('')}</div></section>`;}
export const _test=Object.freeze({clean,esc,level});
