export const XML_COMPARE_TEXT_VALIDATION_RULES_SCHEMA='xml-compare-text-validation-rules/v1';
const clean=(v)=>String(v??'').trim();
const MODES=new Set(['exact-normalized','contains','starts-with','ends-with','regex','regex-position','token-set']);
const MAX_TEXT=5000;
export function normalizeTextMode(value){const mode=clean(value);return MODES.has(mode)?mode:'exact-normalized';}
export function normalizeTextValue(value,options={}){let text=String(value??'');if(options.trim!==false)text=text.trim();if(options.collapseWhitespace!==false)text=text.replace(/\s+/g,' ');if(options.ignorePunctuation)text=text.replace(/[\p{P}\p{S}]+/gu,' ');if(!options.caseSensitive)text=text.toLowerCase();return text;}
export function createDefaultTextRule(field=''){return Object.freeze({field:clean(field),valueType:'text',mode:'exact-normalized',caseSensitive:false,trim:true,collapseWhitespace:true,ignorePunctuation:false,pattern:'',direction:'either-contains',groupSpec:'',compareGroups:Object.freeze([])});}
export function parseRegexGroupSpec(text=''){return Object.freeze(clean(text).split(',').map((part)=>{const m=part.match(/^\s*([^:]+):\s*(\d+)\s*=\s*(\d+)\s*$/);return m?Object.freeze({name:clean(m[1]),sourceGroup:Number(m[2]),targetGroup:Number(m[3])}):null;}).filter(Boolean));}
export function compileTextRule(input={}){const base=createDefaultTextRule(input?.field);return Object.freeze({...base,...input,field:clean(input?.field||base.field),mode:normalizeTextMode(input?.mode),caseSensitive:Boolean(input?.caseSensitive),trim:input?.trim!==false,collapseWhitespace:input?.collapseWhitespace!==false,ignorePunctuation:Boolean(input?.ignorePunctuation),pattern:clean(input?.pattern),direction:clean(input?.direction||base.direction),groupSpec:clean(input?.groupSpec),compareGroups:Object.freeze(input?.compareGroups?.length?input.compareGroups:parseRegexGroupSpec(input?.groupSpec||''))});}
function blank(a,b){return !clean(a)||!clean(b);}
function longText(a,b){return String(a??'').length>MAX_TEXT||String(b??'').length>MAX_TEXT;}
function safeRegex(rule){if(!clean(rule.pattern))return{status:'REGEX_NO_PATTERN'};try{return{regex:new RegExp(rule.pattern,rule.caseSensitive?'':'i')};}catch(error){return{status:'REGEX_INVALID',message:clean(error?.message||error)}}}
function cmpBasic(source,target,rule){const s=normalizeTextValue(source,rule),t=normalizeTextValue(target,rule);if(blank(s,t))return{status:'BLANK',source:s,target:t};if(rule.mode==='contains'){const ok=rule.direction==='target-contains-source'?t.includes(s):rule.direction==='source-contains-target'?s.includes(t):s.includes(t)||t.includes(s);return{status:ok?'OK':'TEXT_CONTAINS_FAIL',source:s,target:t};}if(rule.mode==='starts-with'){const ok=rule.direction==='target-starts-source'?t.startsWith(s):rule.direction==='source-starts-target'?s.startsWith(t):s.startsWith(t)||t.startsWith(s);return{status:ok?'OK':'TEXT_PREFIX_FAIL',source:s,target:t};}if(rule.mode==='ends-with'){const ok=rule.direction==='target-ends-source'?t.endsWith(s):rule.direction==='source-ends-target'?s.endsWith(t):s.endsWith(t)||t.endsWith(s);return{status:ok?'OK':'TEXT_SUFFIX_FAIL',source:s,target:t};}return{status:s===t?'OK':'MISMATCH',source:s,target:t};}
export function compareRegexGroups({sourceValue='',targetValue='',rule={}}={}){const compiled=safeRegex(rule);if(compiled.status)return[{status:compiled.status,field:rule.field}];if(longText(sourceValue,targetValue))return[{status:'TEXT_TOO_LONG',field:rule.field}];const sm=String(sourceValue??'').match(compiled.regex),tm=String(targetValue??'').match(compiled.regex);if(!sm)return[{status:'REGEX_NO_MATCH_SOURCE',field:rule.field}];if(!tm)return[{status:'REGEX_NO_MATCH_TARGET',field:rule.field}];const groups=rule.compareGroups?.length?rule.compareGroups:parseRegexGroupSpec(rule.groupSpec);return groups.map((g)=>{const s=sm[g.sourceGroup],t=tm[g.targetGroup];return{field:rule.field,groupName:g.name,sourceGroupValue:s??'',targetGroupValue:t??'',status:s==null?'REGEX_GROUP_MISSING_SOURCE':t==null?'REGEX_GROUP_MISSING_TARGET':normalizeTextValue(s,rule)===normalizeTextValue(t,rule)?'OK':'REGEX_GROUP_MISMATCH'};});}
export function compareTokenSet({sourceValue='',targetValue='',rule={}}={}){if(longText(sourceValue,targetValue))return{status:'TEXT_TOO_LONG',missingInTarget:[],extraInTarget:[]};const s=normalizeTextValue(sourceValue,rule),t=normalizeTextValue(targetValue,rule);if(blank(s,t))return{status:'BLANK',missingInTarget:[],extraInTarget:[]};const toks=(v)=>new Set(v.split(/[\s,;\/|]+/).map(clean).filter(Boolean));const ss=toks(s),ts=toks(t),missing=[...ss].filter((x)=>!ts.has(x)),extra=[...ts].filter((x)=>!ss.has(x));return{status:missing.length||extra.length?'TOKEN_SET_MISMATCH':'OK',missingInTarget:Object.freeze(missing),extraInTarget:Object.freeze(extra)};}
export function compareTextValues({sourceValue='',targetValue='',rule={}}={}){const r=compileTextRule(rule);if(longText(sourceValue,targetValue))return{status:'TEXT_TOO_LONG'};if(r.mode==='token-set')return compareTokenSet({sourceValue,targetValue,rule:r});if(r.mode==='regex-position')return{status:'REGEX_POSITION',groups:Object.freeze(compareRegexGroups({sourceValue,targetValue,rule:r}))};if(r.mode==='regex'){const c=safeRegex(r);if(c.status)return{status:c.status};const sm=c.regex.test(String(sourceValue??''));const tm=c.regex.test(String(targetValue??''));return{status:!sm?'REGEX_NO_MATCH_SOURCE':!tm?'REGEX_NO_MATCH_TARGET':sm&&tm?'OK':'MISMATCH'};}return cmpBasic(sourceValue,targetValue,r);}
export function createTextValidationRows({sourceRecord=null,targetRecord=null,compareFields=[],textRules={}}={}){const rows=[];for(const field of compareFields||[]){const rule=compileTextRule(textRules?.[field]||{field}),sourceValue=sourceRecord?.[field]??sourceRecord?.fields?.[field]??sourceRecord?.attributes?.[field]??'',targetValue=targetRecord?.[field]??targetRecord?.fields?.[field]??targetRecord?.attributes?.[field]??'',result=compareTextValues({sourceValue,targetValue,rule});if(result.groups){for(const g of result.groups)rows.push({...g,rowType:'text',sourceUid:sourceRecord?.uid||'',targetUid:targetRecord?.uid||'',sourceLabel:sourceRecord?.displayName||sourceRecord?.uid||'',targetLabel:targetRecord?.displayName||targetRecord?.uid||'',mode:'regex-position'});continue;}rows.push({rowType:'text',sourceUid:sourceRecord?.uid||'',targetUid:targetRecord?.uid||'',sourceLabel:sourceRecord?.displayName||sourceRecord?.uid||'',targetLabel:targetRecord?.displayName||targetRecord?.uid||'',field,mode:rule.mode,sourceValue,targetValue,result:result.missingInTarget||result.extraInTarget?`missing=${(result.missingInTarget||[]).join('|')}; extra=${(result.extraInTarget||[]).join('|')}`:'',missingInTarget:result.missingInTarget,extraInTarget:result.extraInTarget,status:result.status});}return Object.freeze(rows);}
