export const XML_COMPARE_HIERARCHY_PROFILER_SCHEMA='xml-compare-hierarchy-profile/v2';
const clean=(v)=>String(v??'').trim();
const uniq=(items)=>Object.freeze([...new Set((items||[]).map(clean).filter(Boolean))]);
const val=(record={},field='')=>field.includes('.')?field.split('.').reduce((obj,key)=>obj?.[key],record):record?.[field];
function fields(records=[]){const keys=[];const add=(key)=>{if(clean(key)&&!keys.includes(key))keys.push(key);};for(const r of records||[])for(const [k,v]of Object.entries(r||{})){if(['raw','rawSummary','diagnostics','points','position','compactFields'].includes(k))continue;if(v==null)continue;if(typeof v==='object'){if(k==='process')for(const pk of Object.keys(v))add(`process.${pk}`);continue;}if(clean(v))add(k);}return Object.freeze(keys);}
function emptyProfile(side,profile,fileName){return Object.freeze({schema:XML_COMPARE_HIERARCHY_PROFILER_SCHEMA,side:clean(side)||'source',profile:clean(profile),fileName:clean(fileName),levels:Object.freeze([]),summary:Object.freeze({levelCount:0,recordCount:0})});}
function rootRecord({side='',fileName='',profile='',summary={}}={}){return Object.freeze({uid:`${clean(side)||'source'}:root`,levelId:'root',recordKind:'ROOT',displayName:clean(fileName)||'Loaded source',key:clean(profile)||'unknown',fileName:clean(fileName),profile:clean(profile),recordCount:Number(summary.recordCount||0),lineCount:Number(summary.lineCount||0),nodeCount:Number(summary.nodeCount||0)});}
function branchRecords(records=[],side='source'){const map=new Map();for(const r of records||[]){const key=clean(r.branchName||r.lineNo||r.pipelineReference||'UNSPECIFIED_BRANCH');const prev=map.get(key)||{source:[],count:0};prev.source.push(r);prev.count+=1;map.set(key,prev);}return Object.freeze([...map.entries()].map(([key,item],i)=>{const first=item.source[0]||{},p=first.process||{};return Object.freeze({uid:`${side}:branch:${key||i+1}`,levelId:'branch',recordKind:'BRANCH',displayName:key,lineNo:clean(first.lineNo||key),branchName:key,key,nodeCount:item.count,materialNumber:clean(p.materialNumber),pressure1:clean(p.pressure1),temperature1:clean(p.temperature1),fluidDensity:clean(p.fluidDensity),raw:Object.freeze({records:item.source})});}));}
function nodeRecords(records=[]){return Object.freeze((records||[]).map((r,i)=>Object.freeze({...r,levelId:'node',recordKind:clean(r.recordKind||'NODE'),displayName:clean(r.displayName||r.nodeName||r.nodeNumber||r.componentRefNo||r.uid||`Node ${i+1}`),key:clean(r.key||r.nodeNumber||r.uid||`node:${i+1}`)})));}
function dtxrEvidence(records=[],side='source'){const out=[];for(const [i,r]of(records||[]).entries()){for(const field of ['dtxrPs','dtxrPos']){const value=clean(r[field]);if(!value)continue;out.push(Object.freeze({uid:`${side}:evidence:${field}:${clean(r.uid)||i+1}`,levelId:'evidence',recordKind:'EVIDENCE',displayName:field==='dtxrPs'?'DTXR_PS':'DTXR_POS',key:value,value,evidenceField:field,branchName:clean(r.branchName),lineNo:clean(r.lineNo||r.branchName),nodeNumber:clean(r.nodeNumber),nodeName:clean(r.nodeName),componentType:clean(r.componentType),componentRefNo:clean(r.componentRefNo),dtxrPs:clean(r.dtxrPs),dtxrPos:clean(r.dtxrPos),position:r.position||null,raw:r}));}}return Object.freeze(out);}
function explicitRecords(records=[],levelId=''){return Object.freeze((records||[]).filter((r)=>clean(r.levelHint||r.levelId)===levelId).map((r)=>Object.freeze({...r,levelId,displayName:clean(r.displayName||r.key||r.uid),key:clean(r.key||r.uid)})));}
function exactLevelRecords(records=[],levelId=''){return Object.freeze((records||[]).filter((r)=>clean(r.levelId)===levelId).map((r)=>Object.freeze({...r,displayName:clean(r.displayName||r.key||r.uid),key:clean(r.key||r.uid)})));}
function dynamicCategorizedLevels(records=[]){const lineBlocks=exactLevelRecords(records,'lineBlock'),elements=exactLevelRecords(records,'element'),nodes=exactLevelRecords(records,'node'),nodeEvidence=exactLevelRecords(records,'nodeEvidence');if(!lineBlocks.length&&!elements.length&&!nodes.length&&!nodeEvidence.length)return null;return Object.freeze({lineBlocks,elements,nodes,nodeEvidence});}
function explicitLevels(records=[]){const dynamic=dynamicCategorizedLevels(records);if(dynamic)return dynamic;const lines=explicitRecords(records,'line'),elements=explicitRecords(records,'element'),nodes=explicitRecords(records,'node'),evidence=explicitRecords(records,'evidence');if(!lines.length&&!elements.length&&!nodes.length&&!evidence.length)return null;return Object.freeze({lines,elements,nodes,evidence});}
function level(levelId,label,type,records,preferred=[],extra={}){const f=uniq([...preferred,...fields(records)]);return Object.freeze({levelId,label,levelType:type,recordCount:records.length,fields:f,records:Object.freeze(records),...extra});}
function categorizedLayout(levelId,records=[]){if(levelId==='lineBlock')return records.length>60?'compact-list':'tiles';if(levelId==='element')return records.length>80?'grouped-compact-tree':'grouped-tree';if(levelId==='node')return records.length>120?'grouped-compact-tree':'grouped-tree';if(levelId==='nodeEvidence')return 'grouped-compact-tree';return 'cards';}
function dynamicLevels(dynamic){return [level('lineBlock','LineBlock','group',dynamic.lineBlocks,['displayName','lineNo','branchName','elementCount','nodeCount','evidenceCount','detectedBlockNames'],{layout:categorizedLayout('lineBlock',dynamic.lineBlocks)}),level('element','Element','occurrence',dynamic.elements,['displayName','elementKey','fromNode','toNode','lineNo','DELTA_X','DELTA_Y','DELTA_Z','ElementLengthMm','MaterialName','nodeCount','evidenceCount'],{layout:categorizedLayout('element',dynamic.elements)}),level('node','Node','occurrence',dynamic.nodes,['displayName','nodeNumber','role','elementKey','lineNo','globalX','globalY','globalZ','Temperature1','Temperature2','Temperature3','restraintCount','displacementsCount','forcesMomentsCount','sifCount'],{layout:categorizedLayout('node',dynamic.nodes)}),level('nodeEvidence','Node Evidence','evidence',dynamic.nodeEvidence,['displayName','evidenceKind','blockName','itemCount','nodeNumber','role','elementKey','lineNo'],{layout:categorizedLayout('nodeEvidence',dynamic.nodeEvidence)})].filter((x)=>x.recordCount);}
export function createXmlCompareHierarchyProfile({side='source',fileName='',profile='unknown',records=[],summary={}}={}){const s=clean(side)||'source';if(!clean(fileName)&&!(records||[]).length)return emptyProfile(s,profile,fileName);const root=[rootRecord({side:s,fileName,profile,summary})],explicit=explicitLevels(records);let levels;if(explicit?.lineBlocks){levels=dynamicLevels(explicit);}else if(explicit){levels=[level('root','Root','container',root,['fileName','profile','recordCount']),level('line','LineBlock','group',explicit.lines,['branchName','lineNo','pipingClass','rating','elementCount']),level('element','Element','occurrence',explicit.elements,['elementKey','fromNode','toNode','displayName','deltaX','deltaY','deltaZ','elementLengthMm','materialName','boreMm']),level('node','Node','occurrence',explicit.nodes,['nodeNumber','role','elementKey','globalX','globalY','globalZ','temperature1','temperature2','temperature3','restraintCount','displacementsCount','forcesMomentsCount','sifCount']),level('evidence','Node Evidence','evidence',explicit.evidence,['evidenceKind','blockName','nodeNumber','role','elementKey','itemCount','branchName','lineNo'])].filter((x)=>x.recordCount||x.levelId==='root');}else{const branches=branchRecords(records,s),nodes=nodeRecords(records),evidence=dtxrEvidence(records,s);levels=[level('root','Root','container',root,['fileName','profile','recordCount']),level('branch','Branch','group',branches,['branchName','lineNo','nodeCount','materialNumber','pressure1','temperature1','fluidDensity']),level('node','Node','occurrence',nodes,['branchName','lineNo','nodeNumber','nodeName','componentType','componentRefNo','position','pipingClass','rating','boreMm','wallThickness','corrosionAllowance','materialName','materialCode','lengthMm','dtxrPs','dtxrPos']),level('evidence','Evidence','evidence',evidence,['evidenceField','value','branchName','lineNo','nodeNumber','componentType','dtxrPs','dtxrPos'])].filter((x)=>x.recordCount||x.levelId==='root');}return Object.freeze({schema:XML_COMPARE_HIERARCHY_PROFILER_SCHEMA,side:s,profile:clean(profile),fileName:clean(fileName),levels:Object.freeze(levels),summary:Object.freeze({levelCount:levels.length,recordCount:records.length})});}
export const _test=Object.freeze({clean,fields,emptyProfile,branchRecords,nodeRecords,dtxrEvidence,explicitRecords,exactLevelRecords,dynamicCategorizedLevels,explicitLevels,categorizedLayout});
