export const XML_COMPARE_ELEMENT_INDEX_SCHEMA='xml-compare-element-index/v1';
const clean=(v)=>String(v??'').trim();
const upper=(v)=>clean(v).toUpperCase();
const arr=(v)=>Array.isArray(v)?v:[];
const num=(v)=>{const n=Number(v);return Number.isFinite(n)?n:null};
function point(v){if(!v)return null;if(Array.isArray(v)&&v.length>=3)return point({x:v[0],y:v[1],z:v[2]});if(typeof v==='string'){const p=v.split(/[\s,]+/).filter(Boolean).map(Number);return p.length>=3?point(p):null}if(typeof v==='object'){const x=num(v.x??v.X),y=num(v.y??v.Y),z=num(v.z??v.Z);return x==null||y==null||z==null?null:Object.freeze({x,y,z})}return null}
function first(...values){for(const v of values){const c=clean(v);if(c)return c}return''}
function delta(component){const a=component.attributes||component.rawAttributes||component.source?.attributes||{};const dx=num(component.deltaX??component.DELTA_X??a.DELTA_X),dy=num(component.deltaY??component.DELTA_Y??a.DELTA_Y),dz=num(component.deltaZ??component.DELTA_Z??a.DELTA_Z);if([dx,dy,dz].every(v=>v!=null))return Object.freeze([dx,dy,dz]);const p0=point(component.points?.[0]),p1=point(component.points?.[1]);return p0&&p1?Object.freeze([p1.x-p0.x,p1.y-p0.y,p1.z-p0.z]):Object.freeze([0,0,0])}
const len=(d)=>Math.hypot(Number(d[0])||0,Number(d[1])||0,Number(d[2])||0);
function uid(side,component,index,record){const base=first(component.uid,component.id,component.componentId,component.source?.id,component.attributes?.componentId,component.attributes?.id);return base?`${side}:${base}`:`${side}:${record.lineId||'line'}:${record.componentType}:${index+1}`}
export function normalizeXmlCompareElementRecord(component={},index=0,{side='source'}={}){const attrs=component.attributes||component.rawAttributes||component.source?.attributes||{};const source=component.source||component.raw||{};const fromPosition=point(component.fromPosition||source.fromPosition||component.points?.[0]);const toPosition=point(component.toPosition||source.toPosition||component.points?.[1]);const position=point(component.position||component.Position||component.centrePoint||component.coOrds||source.position)||((fromPosition&&toPosition)?Object.freeze({x:(fromPosition.x+toPosition.x)/2,y:(fromPosition.y+toPosition.y)/2,z:(fromPosition.z+toPosition.z)/2}):null);const d=delta(component);const record={side:clean(side)||'source',index,lineId:first(component.lineId,component.lineID,component.pipelineRef,attrs.LINE_ID,attrs.lineId,attrs['PIPELINE-REFERENCE'],source.lineId,source.lineNo),fromNode:first(component.fromNode,attrs.FROM_NODE,source.fromNode),toNode:first(component.toNode,attrs.TO_NODE,source.toNode),fromName:first(component.fromName,attrs.FROM_NAME,source.fromName),toName:first(component.toName,attrs.TO_NAME,source.toName),componentType:upper(component.componentType||component.type||attrs.ComponentType||attrs.COMPONENT_TYPE||source.componentType||source.type||'UNKNOWN'),delta:d,lengthMm:len(d),position,fromPosition,toPosition,points:Object.freeze([fromPosition,toPosition].filter(Boolean)),raw:component.raw||component,sceneObject:component.sceneObject||null};return Object.freeze({uid:uid(record.side,component,index,record),...record,psNames:Object.freeze([record.fromName,record.toName].filter(Boolean))})}
function group(records,keyFn){const out={};for(const r of records){const k=clean(keyFn(r));if(!k)continue;(out[k] ||= []).push(r.uid)}return Object.freeze(out)}
export function createXmlCompareElementIndex(components=[],options={}){const side=clean(options.side||'source')||'source';const records=arr(components).map((c,i)=>normalizeXmlCompareElementRecord(c,i,{side}));const diagnostics=[];for(const r of records){if(!r.fromNode&&!r.toNode)diagnostics.push(Object.freeze({code:'XML-COMPARE-ELEMENT-NODES-MISSING',uid:r.uid}));if(!r.position&&!r.points.length)diagnostics.push(Object.freeze({code:'XML-COMPARE-ELEMENT-POSITION-MISSING',uid:r.uid}))}return Object.freeze({schema:XML_COMPARE_ELEMENT_INDEX_SCHEMA,side,records:Object.freeze(records),byUid:Object.freeze(Object.fromEntries(records.map(r=>[r.uid,r]))),byLineId:group(records,r=>r.lineId),byFromName:group(records,r=>r.fromName),byToName:group(records,r=>r.toName),byComponentType:group(records,r=>r.componentType),diagnostics:Object.freeze(diagnostics),summary:Object.freeze({elementCount:records.length,lineCount:Object.keys(group(records,r=>r.lineId)).length,diagnosticCount:diagnostics.length})})}
export const _test=Object.freeze({clean,point,delta,len});
