export const XML_COMPARE_CATEGORIZED_TRANSFER_APPLIER_SCHEMA='xml-compare-categorized-transfer-applier/v2';

const clean=(value)=>String(value??'').trim();
const NODE_REF_ATTRS=Object.freeze(['NODE','NODE_NUM','nodeNumber','nodeRef']);
const OPEN_TAG='(?:[^"\'>]|"[^"]*"|\'[^\']*\')*';
function tagRe(tag=''){return new RegExp(`<${tag}\\b${OPEN_TAG}(?:\\/>|>[\\s\\S]*?<\\/${tag}>)`,'i');}
function tagReGlobal(tag=''){return new RegExp(`<${tag}\\b${OPEN_TAG}(?:\\/>|>[\\s\\S]*?<\\/${tag}>)`,'gi');}
function attrsOf(tag=''){const out={};String(tag).replace(/([A-Za-z_][\w:.-]*)\s*=\s*("([^"]*)"|'([^']*)')/g,(_,key,_q,dq,sq)=>{out[key]=dq??sq??'';return _;});return out;}
function lineIdFromOpen(open=''){const attrs=attrsOf(open);return clean(attrs.id||attrs.lineId||attrs.LINE_ID||'');}
function elementAttrs(open=''){return attrsOf(open);}function elementKey(attrs={}){return clean(attrs.elementKey)||`${clean(attrs.fromNode||attrs.FROM_NODE)}->${clean(attrs.toNode||attrs.TO_NODE)}`;}
function splitLines(xml=''){const text=String(xml??''),rows=[];const re=new RegExp(`<Line\\b${OPEN_TAG}>[\\s\\S]*?<\\/Line>`,'gi');let match;while((match=re.exec(text)))rows.push({start:match.index,end:match.index+match[0].length,xml:match[0],open:match[0].match(new RegExp(`^<Line\\b${OPEN_TAG}>`,'i'))?.[0]||''});return rows;}
function splitElements(lineXml=''){const rows=[];const re=new RegExp(`<Element\\b${OPEN_TAG}>[\\s\\S]*?<\\/Element>`,'gi');let match;while((match=re.exec(String(lineXml))))rows.push({start:match.index,end:match.index+match[0].length,xml:match[0],open:match[0].match(new RegExp(`^<Element\\b${OPEN_TAG}>`,'i'))?.[0]||''});return rows;}
function splitNodes(elementXml=''){const rows=[];const re=new RegExp(`<Node\\b${OPEN_TAG}>[\\s\\S]*?<\\/Node>`,'gi');let match;while((match=re.exec(String(elementXml))))rows.push({start:match.index,end:match.index+match[0].length,xml:match[0],open:match[0].match(new RegExp(`^<Node\\b${OPEN_TAG}>`,'i'))?.[0]||''});return rows;}
function findLine(xml='',lineId=''){const wanted=clean(lineId);return splitLines(xml).find((line)=>lineIdFromOpen(line.open)===wanted)||null;}
function findElement(xml='',elementKeyValue=''){const wanted=clean(elementKeyValue);for(const line of splitLines(xml))for(const element of splitElements(line.xml))if(elementKey(elementAttrs(element.open))===wanted)return {...element,start:line.start+element.start,end:line.start+element.end,line};return null;}
function nodeNumberFromOpen(open=''){const attrs=attrsOf(open);return clean(attrs.nodeNumber||attrs.NODE||attrs.NODE_NUM||attrs.nodeRef||'').replace(/\.0+$/,'');}
function nodeRoleFromOpen(open=''){const attrs=attrsOf(open);return clean(attrs.role||attrs.ROLE||'');}
function findNodeInElement(elementXml='',nodeNumber='',role=''){const wanted=clean(nodeNumber).replace(/\.0+$/,''),wantedRole=clean(role);if(!wanted)return null;for(const node of splitNodes(elementXml)){if(nodeNumberFromOpen(node.open)!==wanted)continue;if(wantedRole&&nodeRoleFromOpen(node.open)&&nodeRoleFromOpen(node.open)!==wantedRole)continue;return node;}return null;}
function findBlock(container='',blockName=''){return String(container).match(tagRe(blockName))?.[0]||'';}
function findBlocks(container='',blockNames=[]){return blockNames.map((name)=>findBlock(container,name)).filter(Boolean);}
function removeBlocks(container='',blockNames=[]){let out=String(container);for(const name of blockNames)out=out.replace(tagReGlobal(name),'');return out;}
function blockNameOf(block=''){return clean(String(block).match(/^<([A-Za-z_][\w:.-]*)\b/)?.[1]||'');}
function blockSummary(block=''){const name=blockNameOf(block),count=(String(block).match(/<[A-Za-z_][\w:.-]*\b/g)||[]).length-1;return {blockName:name,itemCount:Math.max(0,count),xml:clean(block)};}
function replaceRange(text='',start=0,end=0,replacement=''){return `${text.slice(0,start)}${replacement}${text.slice(end)}`;}
function insertBeforeClosing(container='',closeTag='',content=''){const index=container.lastIndexOf(closeTag);if(index<0)return `${container}\n${content}`;return `${container.slice(0,index)}${content}\n${container.slice(index)}`;}
function escapeRegExp(value=''){return String(value).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');}
function rewriteNodeReferences(block='',sourceNode='',targetNode=''){const from=clean(sourceNode),to=clean(targetNode);if(!from||!to)return block;let out=String(block);for(const attr of NODE_REF_ATTRS)out=out.replace(new RegExp(`(${attr}\\s*=\\s*["'])${escapeRegExp(from)}(?:\\.0+)?(["'])`,'gi'),`$1${to}$2`);return out;}
function mergePolicyTarget(target='',incoming='',blockNames=[],policy='replace'){const cleanIncoming=clean(incoming);if(!cleanIncoming)return target;if(policy==='append')return insertBeforeClosing(target,'</Element>',`\n${cleanIncoming}`);if(policy==='skip-existing'&&blockNames.some((block)=>findBlock(target,block)))return target;return insertBeforeClosing(removeBlocks(target,blockNames),'</Element>',`\n${cleanIncoming}`);}
function mergePolicyNode(nodeXml='',incomingBlocks=[],blockNames=[],policy='replace'){const incoming=clean(incomingBlocks.join('\n'));if(!incoming)return nodeXml;if(policy==='append')return insertBeforeClosing(nodeXml,'</Node>',`\n${incoming}`);if(policy==='skip-existing'&&blockNames.some((block)=>findBlock(nodeXml,block)))return nodeXml;return insertBeforeClosing(removeBlocks(nodeXml,blockNames),'</Node>',`\n${incoming}`);}
function updateElement(xml='',elementKeyValue='',updater=(element)=>element){const found=findElement(xml,elementKeyValue);if(!found)return {xml,updated:false,reason:'target-element-not-found'};const next=updater(found.xml);return {xml:replaceRange(xml,found.start,found.end,next),updated:next!==found.xml,before:found.xml,after:next};}
function updateLine(xml='',lineId='',updater=(line)=>line){const found=findLine(xml,lineId);if(!found)return {xml,updated:false,reason:'target-line-not-found'};const next=updater(found.xml);return {xml:replaceRange(xml,found.start,found.end,next),updated:next!==found.xml,before:found.xml,after:next};}
function ensureLineBlocks(lineXml=''){if(/<LineBlocks\b/i.test(lineXml))return lineXml;return lineXml.replace(new RegExp(`(<Line\\b${OPEN_TAG}>)`,'i'),'$1\n  <LineBlocks>\n  </LineBlocks>');}
function updateLineBlocks(lineXml='',blocks=[],policy='replace'){let out=ensureLineBlocks(lineXml);const match=out.match(/<LineBlocks\b[^>]*>[\s\S]*?<\/LineBlocks>/i);if(!match)return out;const blockNames=blocks.map((block)=>clean(block.match(/^<([A-Za-z_][\w:.-]*)/)?.[1]||'')).filter(Boolean);let body=match[0];if(policy!=='append')for(const name of blockNames)body=body.replace(tagReGlobal(name),'');body=body.replace(/<\/LineBlocks>\s*$/i,`${blocks.map((block)=>`\n    ${clean(block)}`).join('')}\n  </LineBlocks>`);return out.replace(match[0],body);}
function sourceBlocksByElement(sourceXml='',elementKeyValue='',blockNames=[]){const found=findElement(sourceXml,elementKeyValue);return found?findBlocks(found.xml,blockNames):[];}
function sourceBlocksByLine(sourceXml='',lineId='',blockNames=[]){const found=findLine(sourceXml,lineId);return found?findBlocks(found.xml,blockNames):[];}
function directNodeBlocks(elementXml='',sourceNode='',blockNames=[],role=''){const node=findNodeInElement(elementXml,sourceNode,role);return node?findBlocks(node.xml,blockNames):[];}
function legacyElementNodeBlocks(elementXml='',sourceNode='',blockNames=[]){const blocks=[];for(const blockName of blockNames){const block=findBlock(elementXml,blockName);if(block&&new RegExp(`\\b(?:NODE|NODE_NUM|nodeNumber|nodeRef)\\s*=\\s*["']${escapeRegExp(clean(sourceNode))}(?:\\.0+)?["']`,'i').test(block))blocks.push(block);}return blocks;}
function sourceNodeBlocks(sourceXml='',sourceNode='',blockNames=[],sourceElement='',sourceRole=''){const blocks=[],candidateElements=[];if(clean(sourceElement)){const found=findElement(sourceXml,sourceElement);if(found)candidateElements.push(found);}if(!candidateElements.length)for(const line of splitLines(sourceXml))candidateElements.push(...splitElements(line.xml));for(const element of candidateElements){const direct=directNodeBlocks(element.xml,sourceNode,blockNames,sourceRole);if(direct.length)blocks.push(...direct);else blocks.push(...legacyElementNodeBlocks(element.xml,sourceNode,blockNames));}return blocks;}
function targetBlockSnapshot(elementXml='',targetNode='',targetRole='',blockNames=[]){const node=findNodeInElement(elementXml,targetNode,targetRole);const container=node?.xml||elementXml;return blockNames.map((name)=>({blockName:name,before:findBlock(container,name)}));}
function updateNodeInElement(elementXml='',targetNode='',targetRole='',incomingBlocks=[],blockNames=[],policy='replace'){const node=findNodeInElement(elementXml,targetNode,targetRole);if(!node)return {xml:mergePolicyTarget(elementXml,incomingBlocks.join('\n'),blockNames,policy),updated:true,reason:'target-node-not-found-used-element-fallback',beforeBlocks:targetBlockSnapshot(elementXml,targetNode,targetRole,blockNames)};const beforeBlocks=targetBlockSnapshot(elementXml,targetNode,targetRole,blockNames);const nextNode=mergePolicyNode(node.xml,incomingBlocks,blockNames,policy);return {xml:replaceRange(elementXml,node.start,node.end,nextNode),updated:nextNode!==node.xml,beforeBlocks};}
function changedBlocks(beforeBlocks=[],afterElement='',targetNode='',targetRole='',blockNames=[]){const node=findNodeInElement(afterElement,targetNode,targetRole);const container=node?.xml||afterElement;return blockNames.map((name)=>{const before=beforeBlocks.find((row)=>row.blockName===name)?.before||'';const after=findBlock(container,name)||'';const status=!before&&after?'added':before&&after&&before!==after?'replaced':before&&!after?'removed':'unchanged';return {blockName:name,status,before:blockSummary(before),after:blockSummary(after)};});}
function approvedBlocksForPair(pair={},allBlockNames=[],approvedPairIds=new Set(),pairId=''){const caseIds=Array.isArray(pair.approvedCaseIds)?pair.approvedCaseIds.map(clean).filter(Boolean):[];if(!approvedPairIds.size)return allBlockNames;if(approvedPairIds.has(pairId))return allBlockNames;const active=caseIds.filter((id)=>approvedPairIds.has(id));if(!active.length)return [];return allBlockNames.filter((blockName)=>active.some((id)=>id.endsWith(`:${blockName}`)));}
export function applyNodeBlockTransfer(targetXml='',sourceXml='',plan={},options={}){const allBlockNames=Array.isArray(plan.selectedBlocks)?plan.selectedBlocks:[];const approvedPairIds=new Set(Array.isArray(plan.approvedPairIds)?plan.approvedPairIds.map(clean).filter(Boolean):[]);let xml=String(targetXml??'');const audit=[];for(const [index,pair] of (plan.pairs||[]).entries()){const pairId=clean(pair.id||pair.pairId||`${pair.sourceNode||''}->${pair.targetNode||''}:${pair.targetElement||''}`)||String(index);const blockNames=approvedBlocksForPair(pair,allBlockNames,approvedPairIds,pairId);if(!blockNames.length){audit.push({scope:'node',pairId,status:'skipped',reason:'not-approved'});continue;}const sourceNode=clean(pair.sourceNode),targetNode=clean(pair.targetNode),sourceElement=clean(pair.sourceElement),targetElementKey=clean(pair.targetElement)||'',sourceRole=clean(pair.sourceRole),targetRole=clean(pair.targetRole||sourceRole);const blocks=sourceNodeBlocks(sourceXml,sourceNode,blockNames,sourceElement,sourceRole).map((block)=>rewriteNodeReferences(block,sourceNode,targetNode));if(!blocks.length){audit.push({scope:'node',pairId,sourceNode,targetNode,status:'skipped',reason:'no-source-node-blocks'});continue;}if(!targetElementKey){audit.push({scope:'node',pairId,sourceNode,targetNode,status:'skipped',reason:'target-element-required'});continue;}let beforeBlocks=[];const result=updateElement(xml,targetElementKey,(element)=>{const next=updateNodeInElement(element,targetNode,targetRole,blocks,blockNames,options.policy||'replace');beforeBlocks=next.beforeBlocks||[];return next.xml;});xml=result.xml;const changed=result.after?changedBlocks(beforeBlocks,result.after,targetNode,targetRole,blockNames):[];audit.push({scope:'node',pairId,sourceNode,targetNode,sourceElement,targetElement:targetElementKey,status:result.updated?'updated':'unchanged',blocks:blockNames,changedBlocks:changed});}return {xml,audit};}
export function applyElementBlockTransfer(targetXml='',sourceXml='',plan={},options={}){const blockNames=Array.isArray(plan.selectedBlocks)?plan.selectedBlocks:[];let xml=String(targetXml??'');const audit=[];for(const pair of plan.pairs||[]){const sourceElement=clean(pair.sourceElement),targetElement=clean(pair.targetElement);const blocks=sourceBlocksByElement(sourceXml,sourceElement,blockNames);if(!blocks.length){audit.push({scope:'element',sourceElement,targetElement,status:'skipped',reason:'no-source-element-blocks'});continue;}const result=updateElement(xml,targetElement,(element)=>mergePolicyTarget(element,blocks.join('\n'),blockNames,options.policy||'replace'));xml=result.xml;audit.push({scope:'element',sourceElement,targetElement,status:result.updated?'updated':'unchanged',blocks:blockNames});}return {xml,audit};}
export function applyLineBlockTransfer(targetXml='',sourceXml='',plan={},options={}){const blockNames=Array.isArray(plan.selectedBlocks)?plan.selectedBlocks:[];let xml=String(targetXml??'');const audit=[];for(const pair of plan.pairs||[]){const sourceLine=clean(pair.sourceLine),targetLine=clean(pair.targetLine);const blocks=sourceBlocksByLine(sourceXml,sourceLine,blockNames);if(!blocks.length){audit.push({scope:'line',sourceLine,targetLine,status:'skipped',reason:'no-source-line-blocks'});continue;}const result=updateLine(xml,targetLine,(line)=>updateLineBlocks(line,blocks,options.policy||'replace'));xml=result.xml;audit.push({scope:'line',sourceLine,targetLine,status:result.updated?'updated':'unchanged',blocks:blockNames});}return {xml,audit};}
export function applyCategorizedTransferPlan(targetXml='',sourceXml='',plan={},options={}){const scope=clean(plan.transferScope||plan.scope);if(scope==='node')return applyNodeBlockTransfer(targetXml,sourceXml,plan,options);if(scope==='element')return applyElementBlockTransfer(targetXml,sourceXml,plan,options);if(scope==='line')return applyLineBlockTransfer(targetXml,sourceXml,plan,options);return {xml:String(targetXml??''),audit:[{scope,status:'skipped',reason:'unsupported-transfer-scope'}]};}
export const _test=Object.freeze({attrsOf,lineIdFromOpen,elementKey,splitLines,splitElements,splitNodes,findLine,findElement,findNodeInElement,findBlock,findBlocks,rewriteNodeReferences,sourceNodeBlocks,sourceBlocksByElement,sourceBlocksByLine,applyCategorizedTransferPlan,blockSummary,changedBlocks,approvedBlocksForPair});
