import { createXmlCompareLineNodeHierarchy } from './XmlCompareLineNodeHierarchy.js';
import { renderXmlCompareCanvasToolbarHtml } from './XmlCompareCanvasToolbar.js';
import { renderXmlCompareHoverCardHtml } from './XmlCompareHoverInspector.js';
import { renderXmlCompareCanvasLevelSelectorHtml } from './XmlCompareCanvasLevelSelector.js';
export const XML_COMPARE_GRAPH_CANVAS_SCHEMA='xml-compare-graph-canvas/v5';
const esc=(v)=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const clean=(v)=>String(v??'').trim();
function value(record={},field=''){return field.includes('.')?field.split('.').reduce((obj,key)=>obj?.[key],record):record?.[field];}
function hierarchy(data={}){return data.hierarchy||createXmlCompareLineNodeHierarchy(data.records||[]);}
function headerText(data={}){return [data.fileName,data.profile,data.levelView?.label].map(esc).filter(Boolean).join(' · ')||'not loaded';}
function nodeTitle(record={}){return record.displayName||record.nodeNumber||record.nodeName||record.uid||'NODE';}
function nodeSubtitle(record={}){return record.lineNo||record.branchName||record.key||'';}
function connected(record={},manualState={}){return (manualState?.connectors||[]).some((c)=>c.sourceUid===record.uid||c.targetUid===record.uid);}
function renderNode(record={},side='source',navState={},manualState={}){const selected=record.uid===navState?.selectedUid,hovered=record.uid===navState?.hoveredUid,pending=side==='source'&&record.uid===manualState?.pendingSourceUid,isConnected=connected(record,manualState);return `<button type="button" class="xml-compare-graph-node ${selected?'is-selected':''} ${hovered?'is-hovered':''} ${pending?'is-pending-source':''} ${isConnected?'is-connected':''}" data-xml-compare-graph-node data-xml-compare-side="${esc(side)}" data-xml-compare-record-uid="${esc(record.uid)}" title="${esc(record.lineNo)} / Node ${esc(record.nodeNumber||record.key)}"><b>${esc(nodeTitle(record))}</b><span>${esc(nodeSubtitle(record))}</span></button>`;}
function renderLine(line={},side='source',navState={},manualState={}){return `<section class="xml-compare-line-group" data-xml-compare-line-no="${esc(line.lineNo)}"><header><b>${esc(line.lineNo)}</b><span>${line.nodes?.length||0} item(s)</span></header><div class="xml-compare-line-node-row">${(line.nodes||[]).map((node)=>renderNode(node,side,navState,manualState)).join('')}</div></section>`;}
function renderField(record={},field=''){const v=value(record,field);if(v==null||typeof v==='object')return '';return clean(v)?`<small><b>${esc(field)}:</b> ${esc(v)}</small>`:'';}
function renderCard(record={},side='source',navState={},manualState={},view={}){const selected=record.uid===navState?.selectedUid,hovered=record.uid===navState?.hoveredUid,isConnected=connected(record,manualState),title=clean(value(record,view.displayField))||nodeTitle(record),subtitle=clean(value(record,view.keyField))||nodeSubtitle(record),fields=(view.fields||[]).filter((field)=>field!==view.displayField&&field!==view.keyField).slice(0,4);return `<button type="button" class="xml-compare-graph-node xml-compare-level-card ${selected?'is-selected':''} ${hovered?'is-hovered':''} ${isConnected?'is-connected':''}" data-xml-compare-record-uid="${esc(record.uid)}" data-xml-compare-side="${esc(side)}"><b>${esc(title)}</b><span>${esc(subtitle)}</span>${fields.map((field)=>renderField(record,field)).join('')}</button>`;}
function renderCards(view={},side='source',navState={},manualState={}){const records=view.records||[];return records.length?`<div class="xml-compare-level-board">${records.map((record)=>renderCard(record,side,navState,manualState,view)).join('')}</div>`:'<div class="xml-compare-graph-empty">No records at selected level</div>';}
function tooltipPairs(record={},fields=[]){return fields.map((field)=>[field,value(record,field)]).filter(([,v])=>v!=null&&typeof v!=='object'&&clean(v));}
function recordTooltip(record={},view={}){let fields=[];if(view.levelId==='lineBlock')fields=['branchName','elementCount','nodeCount','evidenceCount','detectedBlockNames'];else if(view.levelId==='element')fields=['lineNo','fromNode','toNode','DELTA_X','DELTA_Y','DELTA_Z','ElementLengthMm','MaterialName'];else if(view.levelId==='node')fields=['lineNo','elementKey','role','globalX','globalY','globalZ','restraintCount','displacementsCount','forcesMomentsCount','sifCount'];else fields=['lineNo','elementKey','role','nodeNumber','evidenceKind','blockName','itemCount'];return tooltipPairs(record,fields).map(([k,v])=>`${k}: ${Array.isArray(v)?v.join(', '):v}`).join('\n')||clean(record.key||record.uid);}
function dynamicTitle(record={},view={}){if(view.levelId==='lineBlock')return clean(record.lineNo||record.branchName||record.displayName||record.key);if(view.levelId==='element')return clean(record.elementKey||record.displayName||record.key);if(view.levelId==='node')return clean(record.nodeNumber?`Node ${record.nodeNumber}`:record.displayName||record.key);if(view.levelId==='nodeEvidence')return clean(record.evidenceKind||record.blockName||record.displayName||record.key);return clean(value(record,view.displayField))||nodeTitle(record);}
function dynamicSubtitle(record={},view={}){if(view.levelId==='node')return clean(record.role);if(view.levelId==='nodeEvidence')return clean(record.nodeNumber?`${record.role||'Node'} ${record.nodeNumber}`:'');return '';}
function renderDynamicTile(record={},side='source',navState={},manualState={},view={},compact=false){const selected=record.uid===navState?.selectedUid,hovered=record.uid===navState?.hoveredUid,isConnected=connected(record,manualState),title=dynamicTitle(record,view),subtitle=dynamicSubtitle(record,view),tooltip=recordTooltip(record,view);return `<button type="button" class="xml-compare-graph-node xml-compare-dynamic-tile ${compact?'is-compact':''} ${selected?'is-selected':''} ${hovered?'is-hovered':''} ${isConnected?'is-connected':''}" data-xml-compare-record-uid="${esc(record.uid)}" data-xml-compare-side="${esc(side)}" title="${esc(tooltip)}"><b>${esc(title)}</b>${subtitle?`<span>${esc(subtitle)}</span>`:''}</button>`;}
function groupBy(records=[],keyFn){const map=new Map();for(const record of records){const key=clean(keyFn(record))||'Unspecified';if(!map.has(key))map.set(key,[]);map.get(key).push(record);}return [...map.entries()];}
function renderCompactList(view={},side='source',navState={},manualState={}){const records=view.records||[];return records.length?`<div class="xml-compare-dynamic-list">${records.map((record)=>renderDynamicTile(record,side,navState,manualState,view,true)).join('')}</div>`:'<div class="xml-compare-graph-empty">No records at selected level</div>';}
function renderTiles(view={},side='source',navState={},manualState={}){const records=view.records||[];return records.length?`<div class="xml-compare-level-board xml-compare-dynamic-tile-board">${records.map((record)=>renderDynamicTile(record,side,navState,manualState,view,false)).join('')}</div>`:'<div class="xml-compare-graph-empty">No records at selected level</div>';}
function renderElementGroups(records=[],view={},side='source',navState={},manualState={},compact=false){return groupBy(records,(r)=>r.lineNo||r.lineKey||r.branchName).map(([lineNo,items])=>`<section class="xml-compare-dynamic-line-group" data-xml-compare-line-no="${esc(lineNo)}"><header><b>LineBlock ${esc(lineNo)}</b><span>${items.length} element(s)</span></header><div class="xml-compare-dynamic-list">${items.map((record)=>renderDynamicTile(record,side,navState,manualState,view,compact)).join('')}</div></section>`).join('');}
function renderNodeGroups(records=[],view={},side='source',navState={},manualState={},compact=false){return groupBy(records,(r)=>r.lineNo||r.lineKey||r.branchName).map(([lineNo,lineRecords])=>`<section class="xml-compare-dynamic-line-group" data-xml-compare-line-no="${esc(lineNo)}"><header><b>LineBlock ${esc(lineNo)}</b><span>${lineRecords.length} node(s)</span></header>${groupBy(lineRecords,(r)=>r.elementKey).map(([elementKey,nodes])=>`<section class="xml-compare-dynamic-element-group" data-xml-compare-element-key="${esc(elementKey)}"><header><b>Element ${esc(elementKey)}</b><span>${nodes.length} node(s)</span></header><div class="xml-compare-dynamic-list">${nodes.map((record)=>renderDynamicTile(record,side,navState,manualState,view,compact)).join('')}</div></section>`).join('')}</section>`).join('');}
function renderEvidenceGroups(records=[],view={},side='source',navState={},manualState={}){return groupBy(records,(r)=>r.lineNo||r.lineKey||r.branchName).map(([lineNo,lineRecords])=>`<section class="xml-compare-dynamic-line-group" data-xml-compare-line-no="${esc(lineNo)}"><header><b>LineBlock ${esc(lineNo)}</b><span>${lineRecords.length} evidence row(s)</span></header>${groupBy(lineRecords,(r)=>r.elementKey).map(([elementKey,elementRecords])=>`<section class="xml-compare-dynamic-element-group" data-xml-compare-element-key="${esc(elementKey)}"><header><b>Element ${esc(elementKey)}</b><span>${elementRecords.length} evidence row(s)</span></header>${groupBy(elementRecords,(r)=>`${r.role||'NODE'} ${r.nodeNumber||''}`).map(([nodeKey,evidence])=>`<section class="xml-compare-dynamic-node-group" data-xml-compare-node-key="${esc(nodeKey)}"><header><b>Node ${esc(nodeKey)}</b><span>${evidence.length} block(s)</span></header><div class="xml-compare-dynamic-list">${evidence.map((record)=>`<div class="xml-compare-dynamic-evidence-row">${renderDynamicTile(record,side,navState,manualState,view,true)}</div>`).join('')}</div></section>`).join('')}</section>`).join('')}</section>`).join('');}
function renderGroupedTree(view={},side='source',navState={},manualState={},compact=false){const records=view.records||[];if(!records.length)return '<div class="xml-compare-graph-empty">No records at selected level</div>';let body='';if(view.levelId==='element')body=renderElementGroups(records,view,side,navState,manualState,compact);else if(view.levelId==='node')body=renderNodeGroups(records,view,side,navState,manualState,compact);else if(view.levelId==='nodeEvidence')body=renderEvidenceGroups(records,view,side,navState,manualState);else body=renderElementGroups(records,view,side,navState,manualState,compact);return `<div class="xml-compare-dynamic-tree ${compact?'is-compact':''}">${body}</div>`;}
function renderBoard(data={},side='source',navState={},manualState={}){const view=data.levelView||{};if(view.layout==='cards')return renderCards(view,side,navState,manualState);if(view.layout==='tiles')return renderTiles(view,side,navState,manualState);if(view.layout==='compact-list')return renderCompactList(view,side,navState,manualState);if(view.layout==='grouped-tree')return renderGroupedTree(view,side,navState,manualState,false);if(view.layout==='grouped-compact-tree')return renderGroupedTree(view,side,navState,manualState,true);const h=hierarchy(data);return h.lines?.length?`<div class="xml-compare-line-node-board">${h.lines.map((line)=>renderLine(line,side,navState||{},manualState||{})).join('')}</div>`:'<div class="xml-compare-graph-empty">No line/node records loaded</div>';}
function layoutClass(layout=''){if(layout==='cards')return 'is-level-cards';if(layout==='line-node')return 'is-line-node';return `is-${esc(layout||'level-cards')}`;}
export function renderXmlCompareGraphCanvasHtml({side='source',title='',data={},navState=null,manualState=null}={}){const records=data.records||[],activeRecord=records.find((r)=>r.uid===navState?.hoveredUid)||records.find((r)=>r.uid===navState?.selectedUid)||records[0]||null;const layout=data.levelView?.layout||'line-node';return `<section class="xml-compare-graph-canvas-host" data-xml-compare-canvas-host="${esc(side)}"><header><b>${esc(title||side)}</b><span>${headerText(data)}</span></header>${renderXmlCompareCanvasToolbarHtml({side,activeMode:navState?.mode||'select'})}${renderXmlCompareCanvasLevelSelectorHtml({side,levelView:data.levelView})}<div class="xml-compare-graph-canvas ${layoutClass(layout)}" data-xml-compare-graph-canvas="${esc(side)}"><div class="xml-compare-graph-watermark">${esc(side.toUpperCase())}</div>${renderBoard(data,side,navState||{},manualState||{})}</div>${renderXmlCompareHoverCardHtml(activeRecord)}</section>`;}
export const _test=Object.freeze({esc,clean,value,hierarchy,headerText,nodeTitle,nodeSubtitle,recordTooltip,dynamicTitle,dynamicSubtitle,renderCards,renderTiles,renderCompactList,renderGroupedTree,renderDynamicTile});
