export const XML_COMPARE_TRANSFER_PREVIEW_SCHEMA='xml-compare-transfer-preview/v1';
const SKIP=new Set(['uid','raw','points','position','baseRecords','hierarchy','levelProfile','levelView','intake','adapter','diagnostics']);
const NODE_IDENTITY_FIELDS=Object.freeze(['lineNo','elementKey','nodeNumber','role']);
const SEMANTIC_NODE_BLOCK_ORDER=Object.freeze(['DerivedCoordinateBlock','TemperatureBlock','RestraintsBlock','DisplacementsBlock','ForcesMomentsBlock','SifBlock','MiscBlock']);
const clean=(v)=>String(v??'').trim();
function scalar(value){if(value==null)return '';if(typeof value==='object')return '';return clean(value);}
function byUid(records=[],uid=''){return (records||[]).find((record)=>clean(record.uid)===clean(uid))||null;}
function fields(record={}){return Object.freeze(Object.keys(record||{}).filter((field)=>!SKIP.has(field)&&scalar(record[field])));}
function changed(sourceValue='',targetValue=''){return scalar(sourceValue)&&scalar(sourceValue)!==scalar(targetValue);}
function previewRows(sourceRecord={},targetRecord={},connector={}){const rows=[];for(const field of fields(sourceRecord)){const sourceValue=scalar(sourceRecord[field]),targetValue=scalar(targetRecord?.[field]);if(!changed(sourceValue,targetValue))continue;rows.push(Object.freeze({id:`transfer:${clean(connector.id)}:${field}`,connectorId:clean(connector.id),sourceUid:clean(connector.sourceUid),targetUid:clean(connector.targetUid),field,sourceValue,targetValue,status:targetValue?'different':'missing-target-value'}));}return Object.freeze(rows);}
function identityValue(record={},field=''){return clean(record?.[field]);}
function nodeIdentityMatches(selectedNode={},candidate={}){const matched=[];for(const field of NODE_IDENTITY_FIELDS){const sourceValue=identityValue(selectedNode,field),candidateValue=identityValue(candidate,field);if(sourceValue&&candidateValue){if(sourceValue!==candidateValue)return false;matched.push(field);}}
  if(!matched.includes('nodeNumber'))return false;
  if(!matched.includes('elementKey')&&!matched.includes('lineNo'))return false;
  return true;
}
function blockRank(blockName=''){const index=SEMANTIC_NODE_BLOCK_ORDER.indexOf(clean(blockName));return index>=0?index:1000;}
function blockFields(record={}){const fields=record?.compactFields&&typeof record.compactFields==='object'?record.compactFields:{};return Object.freeze({...fields});}
export function getNodeOwnedBlocksForTransfer({selectedNode=null,records=[]}={}){if(!selectedNode)return Object.freeze([]);const seen=new Set();const blocks=[];for(const record of records||[]){if(clean(record?.levelId)!=='nodeEvidence'&&clean(record?.recordKind)!=='NODE_EVIDENCE')continue;if(!nodeIdentityMatches(selectedNode,record))continue;const uid=clean(record.uid)||`${clean(record.lineNo)}:${clean(record.elementKey)}:${clean(record.nodeNumber)}:${clean(record.role)}:${clean(record.blockName)}`;if(seen.has(uid))continue;seen.add(uid);blocks.push(Object.freeze({blockName:clean(record.blockName||record.evidenceKind),evidenceKind:clean(record.evidenceKind||record.blockName),itemCount:Number(record.itemCount||0),sourceUid:uid,fields:blockFields(record),compactFields:blockFields(record),sourceRefs:Object.freeze(record.sourceRefs||[]),transferEligible:true,lineNo:clean(record.lineNo),elementKey:clean(record.elementKey),nodeNumber:clean(record.nodeNumber),role:clean(record.role)}));}
  blocks.sort((a,b)=>blockRank(a.blockName)-blockRank(b.blockName)||a.blockName.localeCompare(b.blockName,undefined,{numeric:true,sensitivity:'base'}));
  return Object.freeze(blocks);
}
function allSourceRecords(source=null){return Object.freeze([...(source?.baseRecords||[]),...(source?.intake?.records||[]),...(source?.records||[])]);}
function nodeBlockDiagnostics(sourceRecord=null,blocks=[]){if(!sourceRecord||clean(sourceRecord.levelId)!=='node')return Object.freeze([]);if(blocks.length)return Object.freeze([]);return Object.freeze([{severity:'INFO',code:'node_owned_blocks_not_found',message:'No node-owned blocks found for selected node identity.',identity:Object.freeze({lineNo:clean(sourceRecord.lineNo),elementKey:clean(sourceRecord.elementKey),nodeNumber:clean(sourceRecord.nodeNumber),role:clean(sourceRecord.role)})}]);}
export function createXmlCompareTransferPreview({source=null,target=null,manualConnectors=[]}={}){const rows=[],nodeOwnedBlocks=[],diagnostics=[];const sourceRecords=allSourceRecords(source);for(const connector of manualConnectors||[]){const sourceRecord=byUid(source?.records||[],connector.sourceUid)||byUid(sourceRecords,connector.sourceUid),targetRecord=byUid(target?.records||[],connector.targetUid);if(!sourceRecord||!targetRecord)continue;rows.push(...previewRows(sourceRecord,targetRecord,connector));const blocks=getNodeOwnedBlocksForTransfer({selectedNode:sourceRecord,records:sourceRecords});nodeOwnedBlocks.push(...blocks.map((block)=>Object.freeze({...block,connectorId:clean(connector.id),targetUid:clean(connector.targetUid)})));diagnostics.push(...nodeBlockDiagnostics(sourceRecord,blocks));}return Object.freeze({schema:XML_COMPARE_TRANSFER_PREVIEW_SCHEMA,rows:Object.freeze(rows),nodeOwnedBlocks:Object.freeze(nodeOwnedBlocks),diagnostics:Object.freeze(diagnostics),summary:Object.freeze({connectorCount:(manualConnectors||[]).length,previewCount:rows.length,nodeOwnedBlockCount:nodeOwnedBlocks.length,diagnosticCount:diagnostics.length})});}
export const _test=Object.freeze({clean,scalar,byUid,fields,changed,previewRows,nodeIdentityMatches,getNodeOwnedBlocksForTransfer,allSourceRecords,nodeBlockDiagnostics});
