import { adaptCiiEnrichedStageToCompareRecords } from './XmlCompareCiiEnrichedStageAdapter.js';
export const XML_COMPARE_CII_ENRICHED_XML_ADAPTER_SCHEMA='xml-compare-cii-enriched-xml-adapter/v1';
const clean=(v)=>String(v??'').trim();
const blocks=(xml,name)=>[...clean(xml).matchAll(new RegExp(`<${name}\\b[^>]*>([\\s\\S]*?)<\\/${name}>`,'gi'))].map((m)=>m[1]);
const tag=(xml,name)=>clean(clean(xml).match(new RegExp(`<${name}\\b[^>]*>([\\s\\S]*?)<\\/${name}>`,'i'))?.[1]?.replace(/<[^>]+>/g,''));
function local(node){return clean(node?.localName||node?.nodeName).replace(/^.*:/,'');}
function children(parent,name){return [...(parent?.childNodes||[])].filter((n)=>n.nodeType===1&&local(n)===name);}
function first(parent,name){return children(parent,name)[0]||null;}
function txt(parent,name){return clean(first(parent,name)?.textContent);}
function map(parent){const out={};for(const child of [...(parent?.childNodes||[])])if(child.nodeType===1)out[local(child)]=clean(child.textContent);return out;}
function mapBlock(xml){const out={};for(const match of clean(xml).matchAll(/<([A-Za-z0-9_:-]+)\b[^>]*>([\s\S]*?)<\/\1>/g))out[match[1].replace(/^.*:/,'')]=clean(match[2].replace(/<[^>]+>/g,''));return out;}
function nodeRecordFromDom(node){return {nodeNumber:txt(node,'NodeNumber'),nodeName:txt(node,'NodeName'),endpoint:txt(node,'Endpoint'),rigid:txt(node,'Rigid'),componentType:txt(node,'ComponentType'),connectionType:txt(node,'ConnectionType'),weight:txt(node,'Weight'),componentRefNo:txt(node,'ComponentRefNo'),outsideDiameter:txt(node,'OutsideDiameter'),wallThickness:txt(node,'WallThickness'),corrosionAllowance:txt(node,'CorrosionAllowance'),insulationThickness:txt(node,'InsulationThickness'),position:txt(node,'Position'),bendRadius:txt(node,'BendRadius'),sif:txt(node,'SIF'),pipingClass:txt(node,'PipingClass'),rating:txt(node,'Rating'),boreMm:txt(node,'BoreMm'),materialName:txt(node,'MaterialName'),materialCode:txt(node,'MaterialCode'),elementLengthMm:txt(node,'ElementLengthMm'),dtxrPs:txt(node,'DTXR_PS'),dtxrPos:txt(node,'DTXR_POS')};}
function nodeRecordFromBlock(xml){return {nodeNumber:tag(xml,'NodeNumber'),nodeName:tag(xml,'NodeName'),endpoint:tag(xml,'Endpoint'),rigid:tag(xml,'Rigid'),componentType:tag(xml,'ComponentType'),connectionType:tag(xml,'ConnectionType'),weight:tag(xml,'Weight'),componentRefNo:tag(xml,'ComponentRefNo'),outsideDiameter:tag(xml,'OutsideDiameter'),wallThickness:tag(xml,'WallThickness'),corrosionAllowance:tag(xml,'CorrosionAllowance'),insulationThickness:tag(xml,'InsulationThickness'),position:tag(xml,'Position'),bendRadius:tag(xml,'BendRadius'),sif:tag(xml,'SIF'),pipingClass:tag(xml,'PipingClass'),rating:tag(xml,'Rating'),boreMm:tag(xml,'BoreMm'),materialName:tag(xml,'MaterialName'),materialCode:tag(xml,'MaterialCode'),elementLengthMm:tag(xml,'ElementLengthMm'),dtxrPs:tag(xml,'DTXR_PS'),dtxrPos:tag(xml,'DTXR_POS')};}
function stageFromDom(xmlText){const document=new DOMParser().parseFromString(clean(xmlText),'application/xml');if(document.getElementsByTagName('parsererror').length)throw new Error('Invalid XML->CII enriched XML.');return [...document.getElementsByTagName('Branch')].map((branch)=>({branchName:txt(branch,'Branchname'),pipelineReference:txt(branch,'PipelineReference'),lineNo:txt(branch,'LineNo'),pressure:map(first(branch,'Pressure')),temperature:map(first(branch,'Temperature')),materialNumber:txt(branch,'MaterialNumber'),insulationDensity:txt(branch,'InsulationDensity'),fluidDensity:txt(branch,'FluidDensity'),nodes:children(branch,'Node').map(nodeRecordFromDom)}));}
function stageFromText(xmlText){return blocks(xmlText,'Branch').map((branch)=>({branchName:tag(branch,'Branchname'),pipelineReference:tag(branch,'PipelineReference'),lineNo:tag(branch,'LineNo'),pressure:mapBlock(blocks(branch,'Pressure')[0]||''),temperature:mapBlock(blocks(branch,'Temperature')[0]||''),materialNumber:tag(branch,'MaterialNumber'),insulationDensity:tag(branch,'InsulationDensity'),fluidDensity:tag(branch,'FluidDensity'),nodes:blocks(branch,'Node').map(nodeRecordFromBlock)}));}
export function ciiEnrichedXmlToStage(xmlText,{source='',enrichedXml=''}={}){const branches=typeof DOMParser==='undefined'?stageFromText(xmlText):stageFromDom(xmlText);return Object.freeze({schema:'xml-cii2019-enriched-stage/v1',profile:'XML_CII_2019_RICH_WORKFLOW',converter:'XML->CII(2019)',source,enrichedXml,branches:Object.freeze(branches)});}
export function adaptCiiEnrichedXmlToCompareRecords(xmlText,options={}){const stage=ciiEnrichedXmlToStage(xmlText,{source:options.sourceName||'',enrichedXml:options.enrichedName||options.sourceName||''});const adapted=adaptCiiEnrichedStageToCompareRecords(stage,options);return Object.freeze({...adapted,schema:XML_COMPARE_CII_ENRICHED_XML_ADAPTER_SCHEMA,profile:'xml-cii2019-enriched-xml',sourceStageSchema:stage.schema});}
export const _test=Object.freeze({clean,blocks,tag,mapBlock,nodeRecordFromBlock});
