export const XML_COMPARE_CONNECTOR_CANDIDATE_MODEL_SCHEMA='xml-compare-connector-candidate-model/v3';
const clean=(v)=>String(v??'').trim();
function val(record={},field=''){return clean(field).includes('.')?clean(field).split('.').reduce((obj,key)=>obj?.[key],record):record?.[field];}
function scalar(record={},field=''){const v=val(record,field);if(v==null)return '';if(typeof v==='object'){if(['x','y','z'].every((key)=>v[key]!=null))return [v.x,v.y,v.z].map((n)=>Number(n).toFixed(3)).join(',');return '';}return clean(v);}
function norm(text=''){return clean(text).replace(/\s+/g,' ').toUpperCase();}
function label(record={}){return clean(record.displayName||record.elementKey||record.nodeName||record.nodeNumber||record.branchName||record.value||record.uid);}
const COMMON_FIELDS=Object.freeze(['dtxrPs','dtxrPos','value','lineNo','branchName','nodeNumber','nodeName','componentRefNo','pipingClass','rating','elementKey','fromNode','toNode','role','evidenceKind','blockName','materialName','boreMm','deltaX','deltaY','deltaZ','globalX','globalY','globalZ']);
const LEVEL_FIELDS=Object.freeze({line:['lineNo','branchName','pipingClass','rating'],branch:['lineNo','branchName','pipingClass','rating'],element:['elementKey','fromNode','toNode','materialName','boreMm','deltaX','deltaY','deltaZ','elementLengthMm'],node:['elementKey','nodeNumber','role','globalX','globalY','globalZ','temperature1','temperature2','temperature3','restraintCount','displacementsCount','forcesMomentsCount','sifCount'],evidence:['elementKey','nodeNumber','role','evidenceKind','blockName','itemCount','dtxrPs','dtxrPos','value']});
function levelRecords(side={}){const view=side?.levelView||{},levelId=clean(view.levelId);const levels=view.hierarchyProfile?.levels||[];const active=levels.find((level)=>level.levelId===levelId);return Object.freeze(active?.records||view.records||side.records||[]);}
function fields(view={}){const levelId=clean(view.levelId);return Object.freeze([view.keyField,view.displayField,...(LEVEL_FIELDS[levelId]||[]),...(view.fields||[]).filter((field)=>COMMON_FIELDS.includes(field))].map(clean).filter(Boolean));}
function scoreFor(basis=''){if(basis==='KEY')return 1;if(basis==='DISPLAY')return .9;if(basis.startsWith('LEVEL:'))return .86;return .82;}
function fieldPairs(sourceView={},targetView={}){const pairs=[];const add=(sourceField,targetField,basis)=>{if(sourceField&&targetField&&!pairs.some((p)=>p.sourceField===sourceField&&p.targetField===targetField))pairs.push(Object.freeze({sourceField,targetField,basis,score:scoreFor(basis)}));};add(sourceView.keyField,targetView.keyField,'KEY');add(sourceView.displayField,targetView.displayField,'DISPLAY');const sf=new Set(fields(sourceView)),tf=new Set(fields(targetView));for(const field of sf)if(tf.has(field))add(field,field,`LEVEL:${clean(sourceView.levelId)||'field'}:${field}`);return Object.freeze(pairs);}
function candidateId(a={},b={},pair={}){return `candidate:${clean(a.uid)}=>${clean(b.uid)}:${pair.sourceField}:${pair.targetField}`;}
function makeCandidate(a,b,pair){const sourceValue=scalar(a,pair.sourceField),targetValue=scalar(b,pair.targetField);if(!sourceValue||!targetValue||norm(sourceValue)!==norm(targetValue))return null;return Object.freeze({id:candidateId(a,b,pair),type:'CANDIDATE',locked:false,sourceUid:clean(a.uid),targetUid:clean(b.uid),sourceLabel:label(a),targetLabel:label(b),sourceField:pair.sourceField,targetField:pair.targetField,sourceValue,targetValue,basis:Object.freeze([pair.basis]),score:pair.score});}
function dedupe(candidates=[]){const seen=new Set(),out=[];for(const c of candidates){const key=`${c.sourceUid}->${c.targetUid}`;const prev=out.find((item)=>`${item.sourceUid}->${item.targetUid}`===key);if(prev){if(c.score>prev.score){const i=out.indexOf(prev);out[i]=c;}continue;}if(!seen.has(key)){seen.add(key);out.push(c);}}return out;}
function emptyModel(sourceView={},targetView={},reason='manual-first'){return Object.freeze({schema:XML_COMPARE_CONNECTOR_CANDIDATE_MODEL_SCHEMA,candidates:Object.freeze([]),summary:Object.freeze({candidateCount:0,sourceLevel:clean(sourceView.levelId),targetLevel:clean(targetView.levelId),fieldPairCount:0,sourceRecordCount:0,targetRecordCount:0,enabled:false,reason})});}
export function createXmlCompareConnectorCandidateModel({source=null,target=null,limit=40,enabled=false}={}){const sourceView=source?.levelView||{},targetView=target?.levelView||{};if(!enabled)return emptyModel(sourceView,targetView);const pairs=fieldPairs(sourceView,targetView),sourceRecords=levelRecords(source),targetRecords=levelRecords(target),raw=[];for(const pair of pairs)for(const a of sourceRecords)for(const b of targetRecords){const c=makeCandidate(a,b,pair);if(c)raw.push(c);}const candidates=dedupe(raw).sort((a,b)=>b.score-a.score||a.sourceLabel.localeCompare(b.sourceLabel)).slice(0,Math.max(0,Number(limit)||40));return Object.freeze({schema:XML_COMPARE_CONNECTOR_CANDIDATE_MODEL_SCHEMA,candidates:Object.freeze(candidates),summary:Object.freeze({candidateCount:candidates.length,sourceLevel:clean(sourceView.levelId),targetLevel:clean(targetView.levelId),fieldPairCount:pairs.length,sourceRecordCount:sourceRecords.length,targetRecordCount:targetRecords.length,enabled:true,reason:'enabled'})});}
export const _test=Object.freeze({clean,val,scalar,norm,label,fields,fieldPairs,levelRecords,makeCandidate,dedupe,emptyModel});
