export const XML_COMPARE_CONNECTOR_OVERLAY_SCHEMA='xml-compare-connector-overlay/v2';
const esc=(v)=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const arr=(v)=>Array.isArray(v)?v:[];
function link(match={},index=0){return Object.freeze({id:String(match.id||`match-${index+1}`),sourceUid:String(match.sourceUid||''),targetUid:String(match.targetUid||''),status:String(match.status||'accepted'),basis:arr(match.basis),confidence:Number(match.confidence||0),orientation:String(match.orientation||'source-target'),locked:Boolean(match.locked),sourceLabel:String(match.sourceLabel||match.sourceUid||''),targetLabel:String(match.targetLabel||match.targetUid||'')});}
function pending(sourceUid='',targetUid=''){if(!sourceUid&&!targetUid)return null;return Object.freeze({id:'pending-manual',sourceUid,targetUid,status:targetUid?'preview':'pending-source',basis:Object.freeze(['manual']),confidence:targetUid?1:0,orientation:'source-target',locked:false,sourceLabel:sourceUid,targetLabel:targetUid||'Pick target'});}
export function createXmlCompareConnectorOverlayModel({matchMap=null,manualConnectors=[],navStates={}}={}){const autoLinks=arr(matchMap?.matches).map(link);const manualLinks=arr(manualConnectors).map(link);const pendingLink=pending(navStates?.source?.selectedUid||'',navStates?.target?.selectedUid||'');const links=Object.freeze([...autoLinks,...manualLinks,...(pendingLink&&!manualLinks.some((item)=>item.sourceUid===pendingLink.sourceUid&&item.targetUid===pendingLink.targetUid)?[pendingLink]:[])]);const summary=matchMap?.summary||{};return Object.freeze({schema:XML_COMPARE_CONNECTOR_OVERLAY_SCHEMA,links,summary:Object.freeze({matchCount:Number(summary.matchCount||autoLinks.length),manualCount:manualLinks.length,ambiguousCount:Number(summary.ambiguousCount||0),conflictCount:Number(summary.conflictCount||0),rejectedCount:Number(summary.rejectedCount||0)})});}
function line(item,index,total){const y=total<=1?50:16+index*(68/Math.max(1,total-1));const cls=`connector-${esc(item.status)}`;const label=item.locked?'MANUAL':(item.basis[0]||item.status||'LINK');return `<g data-xml-compare-connector="${esc(item.id)}" class="${cls}"><path d="M 4 ${y} C 32 ${Math.max(8,y-18)}, 68 ${Math.min(92,y+18)}, 96 ${y}"/><circle cx="4" cy="${y}" r="2.5"/><circle cx="96" cy="${y}" r="2.5"/><text x="50" y="${Math.max(10,y-5)}">${esc(label)}</text></g>`;}
export function renderXmlCompareConnectorOverlayHtml(input={}){const model=createXmlCompareConnectorOverlayModel(input);return `<div class="xml-compare-connector-overlay-panel" data-xml-compare-connector-overlay><div class="xml-compare-connector-summary"><b>Manual</b><span>${model.summary.manualCount}</span><b>Auto</b><span>${model.summary.matchCount}</span><b>Conflicts</b><span>${model.summary.conflictCount}</span></div>${model.links.length?`<svg viewBox="0 0 100 100" preserveAspectRatio="none" class="xml-compare-connector-overlay-svg">${model.links.map((item,index)=>line(item,index,model.links.length)).join('')}</svg>`:'<div class="xml-compare-empty">Pick Source, then Target to create a connector.</div>'}</div>`;}
export const _test=Object.freeze({esc,arr,link,pending});
